type Warframe = {
  name: string;
  type: "prime" | "standard";
  id: number;
};

export const warframes: Warframe[] = [
  { id: 1, name: "Ash", type: "standard" },
  { id: 2, name: "Ash Prime", type: "prime" },
  { id: 3, name: "Atlas", type: "standard" },
  { id: 4, name: "Atlas Prime", type: "prime" },
  { id: 5, name: "Banshee", type: "standard" },
  { id: 6, name: "Banshee Prime", type: "prime" },
  { id: 7, name: "Baruuk", type: "standard" },
  { id: 8, name: "Baruuk Prime", type: "prime" },
  { id: 9, name: "Caliban", type: "standard" },
  { id: 10, name: "Chroma", type: "standard" },
  { id: 11, name: "Chroma Prime", type: "prime" },
  { id: 12, name: "Citrine", type: "standard" },
  { id: 13, name: "Dagath", type: "standard" },
  { id: 14, name: "Dante", type: "standard" },
  { id: 15, name: "Ember", type: "standard" },
  { id: 16, name: "Ember Prime", type: "prime" },
  { id: 17, name: "Equinox", type: "standard" },
  { id: 18, name: "Equinox Prime", type: "prime" },
  { id: 19, name: "Excalibur", type: "standard" },
  { id: 20, name: "Excalibur Prime", type: "prime" },
  { id: 21, name: "Excalibur Umbra", type: "standard" },
  { id: 22, name: "Frost", type: "standard" },
  { id: 23, name: "Frost Prime", type: "prime" },
  { id: 24, name: "Gara", type: "standard" },
  { id: 25, name: "Gara Prime", type: "prime" },
  { id: 26, name: "Garuda", type: "standard" },
  { id: 27, name: "Garuda Prime", type: "prime" },
  { id: 28, name: "Gauss", type: "standard" },
  { id: 29, name: "Gauss Prime", type: "prime" },
  { id: 30, name: "Grendel", type: "standard" },
  { id: 31, name: "Grendel Prime", type: "prime" },
  { id: 32, name: "Gyre", type: "standard" },
  { id: 33, name: "Harrow", type: "standard" },
  { id: 34, name: "Harrow Prime", type: "prime" },
  { id: 35, name: "Hildryn", type: "standard" },
  { id: 36, name: "Hildryn Prime", type: "prime" },
  { id: 37, name: "Hydroid", type: "standard" },
  { id: 38, name: "Hydroid Prime", type: "prime" },
  { id: 39, name: "Inaros", type: "standard" },
  { id: 40, name: "Inaros Prime", type: "prime" },
  { id: 41, name: "Ivara", type: "standard" },
  { id: 42, name: "Ivara Prime", type: "prime" },
  { id: 43, name: "Jade", type: "standard" },
  { id: 44, name: "Khora", type: "standard" },
  { id: 45, name: "Khora Prime", type: "prime" },
  { id: 46, name: "Kullervo", type: "standard" },
  { id: 47, name: "Lavos", type: "standard" },
  { id: 48, name: "Limbo", type: "standard" },
  { id: 49, name: "Limbo Prime", type: "prime" },
  { id: 50, name: "Loki", type: "standard" },
  { id: 51, name: "Loki Prime", type: "prime" },
  { id: 52, name: "Mag", type: "standard" },
  { id: 53, name: "Mag Prime", type: "prime" },
  { id: 54, name: "Mesa", type: "standard" },
  { id: 55, name: "Mesa Prime", type: "prime" },
  { id: 56, name: "Mirage", type: "standard" },
  { id: 57, name: "Mirage Prime", type: "prime" },
  { id: 58, name: "Nekros", type: "standard" },
  { id: 59, name: "Nekros Prime", type: "prime" },
  { id: 60, name: "Nezha", type: "standard" },
  { id: 61, name: "Nezha Prime", type: "prime" },
  { id: 62, name: "Nidus", type: "standard" },
  { id: 63, name: "Nidus Prime", type: "prime" },
  { id: 64, name: "Nova", type: "standard" },
  { id: 65, name: "Nova Prime", type: "prime" },
  { id: 66, name: "Nyx", type: "standard" },
  { id: 67, name: "Nyx Prime", type: "prime" },
  { id: 68, name: "Oberon", type: "standard" },
  { id: 69, name: "Oberon Prime", type: "prime" },
  { id: 70, name: "Octavia", type: "standard" },
  { id: 71, name: "Octavia Prime", type: "prime" },
  { id: 72, name: "Protea", type: "standard" },
  { id: 73, name: "Protea Prime", type: "prime" },
  { id: 74, name: "Qorvex", type: "standard" },
  { id: 75, name: "Revenant", type: "standard" },
  { id: 76, name: "Revenant Prime", type: "prime" },
  { id: 77, name: "Rhino", type: "standard" },
  { id: 78, name: "Rhino Prime", type: "prime" },
  { id: 79, name: "Saryn", type: "standard" },
  { id: 80, name: "Saryn Prime", type: "prime" },
  { id: 81, name: "Sevagoth", type: "standard" },
  { id: 82, name: "Sevagoth Prime", type: "prime" },
  { id: 83, name: "Sevagoth's Shadow", type: "standard" },
  { id: 84, name: "Styanax", type: "standard" },
  { id: 85, name: "Titania", type: "standard" },
  { id: 86, name: "Titania Prime", type: "prime" },
  { id: 87, name: "Trinity", type: "standard" },
  { id: 88, name: "Trinity Prime", type: "prime" },
  { id: 89, name: "Valkyr", type: "standard" },
  { id: 90, name: "Valkyr Prime", type: "prime" },
  { id: 91, name: "Vauban", type: "standard" },
  { id: 92, name: "Vauban Prime", type: "prime" },
  { id: 93, name: "Volt", type: "standard" },
  { id: 94, name: "Volt Prime", type: "prime" },
  { id: 95, name: "Voruna", type: "standard" },
  { id: 96, name: "Wisp", type: "standard" },
  { id: 97, name: "Wisp Prime", type: "prime" },
  { id: 98, name: "Wukong", type: "standard" },
  { id: 99, name: "Wukong Prime", type: "prime" },
  { id: 100, name: "Xaku", type: "standard" },
];
