type Weapon = {
  name: string;
  category: string;
  type: "prime" | "standard";
  id: number;
};

export const weaponList: Weapon[] = [
  { name: "AX-52", category: "Assault Rifle", type: "standard", id: 201 },
  { name: "Acceltra", category: "Assault Rifle", type: "standard", id: 202 },
  { name: "Acceltra Prime", category: "Assault Rifle", type: "prime", id: 203 },
  {
    name: "Ack & Brunt",
    category: "Sword And Shield",
    type: "standard",
    id: 4,
  },
  { name: "Acrid", category: "Pistol", type: "standard", id: 205 },
  { name: "Aegrit", category: "Thrown", type: "standard", id: 206 },
  { name: "Aeolak", category: "Assault Rifle", type: "standard", id: 207 },
  { name: "Afentis", category: "Speargun", type: "standard", id: 208 },
  { name: "Afuris", category: "Pistol", type: "standard", id: 209 },
  { name: "Afuris Prime", category: "Pistol", type: "prime", id: 210 },
  { name: "Agkuza", category: "MELEE", type: "standard", id: 211 },
  { name: "Akarius", category: "Pistol", type: "standard", id: 212 },
  { name: "Akarius Prime", category: "Pistol", type: "prime", id: 213 },
  { name: "Akaten", category: "MELEE", type: "standard", id: 214 },
  { name: "Akbolto", category: "Pistol", type: "standard", id: 215 },
  { name: "Akbolto Prime", category: "Pistol", type: "prime", id: 216 },
  { name: "Akbronco", category: "Pistol", type: "standard", id: 217 },
  { name: "Akbronco Prime", category: "Pistol", type: "prime", id: 218 },
  { name: "Akjagara", category: "Pistol", type: "standard", id: 219 },
  { name: "Akjagara Prime", category: "Pistol", type: "prime", id: 220 },
  { name: "Aklato", category: "Pistol", type: "standard", id: 221 },
  { name: "Aklex", category: "Pistol", type: "standard", id: 222 },
  { name: "Aklex Prime", category: "Pistol", type: "prime", id: 223 },
  { name: "Akmagnus", category: "Pistol", type: "standard", id: 224 },
  { name: "Akmagnus Prime", category: "Pistol", type: "prime", id: 225 },
  { name: "Aksomati", category: "Pistol", type: "standard", id: 226 },
  { name: "Aksomati Prime", category: "Pistol", type: "prime", id: 227 },
  { name: "Akstiletto", category: "Pistol", type: "standard", id: 228 },
  { name: "Akstiletto Prime", category: "Pistol", type: "prime", id: 229 },
  { name: "Akvasto", category: "Pistol", type: "standard", id: 230 },
  { name: "Akvasto Prime", category: "Pistol", type: "prime", id: 231 },
  { name: "Akzani", category: "Pistol", type: "standard", id: 232 },
  { name: "Alternox", category: "Assault Rifle", type: "standard", id: 233 },
  { name: "Ambassador", category: "Assault Rifle", type: "standard", id: 234 },
  { name: "Amphis", category: "Staves", type: "standard", id: 235 },
  { name: "Amprex", category: "Assault Rifle", type: "standard", id: 236 },
  { name: "Angstrum", category: "Pistol", type: "standard", id: 237 },
  { name: "Anku", category: "Scythes", type: "standard", id: 238 },
  { name: "Ankyros", category: "Fists", type: "standard", id: 239 },
  { name: "Ankyros Prime", category: "Fists", type: "prime", id: 240 },
  { name: "Arca Plasmor", category: "Shotgun", type: "standard", id: 241 },
  { name: "Arca Scisco", category: "Pistol", type: "standard", id: 242 },
  { name: "Arca Titron", category: "Hammers", type: "standard", id: 243 },
  {
    name: "Argo & Vel",
    category: "Sword And Shield",
    type: "standard",
    id: 244,
  },
  { name: "Argonak", category: "Assault Rifle", type: "standard", id: 245 },
  { name: "Arquebex", category: "Archgun", type: "standard", id: 246 },
  { name: "Artax", category: "SENTINEL WEAPON", type: "standard", id: 247 },
  { name: "Artemis Bow", category: "Bow", type: "standard", id: 248 },
  { name: "Artemis Bow Prime", category: "Bow", type: "prime", id: 249 },
  { name: "Arum Spinosa", category: "Warfans", type: "standard", id: 250 },
  { name: "Astilla", category: "Shotgun", type: "standard", id: 251 },
  { name: "Astilla Prime", category: "Shotgun", type: "prime", id: 252 },
  { name: "Athodai", category: "Pistol", type: "standard", id: 253 },
  { name: "Atomos", category: "Pistol", type: "standard", id: 254 },
  { name: "Atterax", category: "Whips", type: "standard", id: 255 },
  { name: "Attica", category: "Bow", type: "standard", id: 256 },
  { name: "Azima", category: "Pistol", type: "standard", id: 257 },
  {
    name: "Azothane",
    category: "Two-Handed Nikana",
    type: "standard",
    id: 258,
  },
  { name: "Balefire Charger", category: "Pistol", type: "standard", id: 259 },
  {
    name: "Balefire Charger Prime",
    category: "Pistol",
    type: "prime",
    id: 260,
  },
  { name: "Balla", category: "Zaw", type: "standard", id: 261 },
  { name: "Ballistica", category: "Pistol", type: "standard", id: 262 },
  { name: "Ballistica Prime", category: "Pistol", type: "prime", id: 263 },
  { name: "Basmu", category: "Assault Rifle", type: "standard", id: 264 },
  { name: "Batoten", category: "MELEE", type: "standard", id: 265 },
  { name: "Battacor", category: "Assault Rifle", type: "standard", id: 266 },
  { name: "Baza", category: "Assault Rifle", type: "standard", id: 267 },
  { name: "Baza Prime", category: "Assault Rifle", type: "prime", id: 268 },
  { name: "Bo", category: "Staves", type: "standard", id: 269 },
  { name: "Bo Prime", category: "Staves", type: "prime", id: 270 },
  { name: "Boar", category: "Shotgun", type: "standard", id: 271 },
  { name: "Boar Prime", category: "Shotgun", type: "prime", id: 272 },
  { name: "Boltace", category: "Tonfas", type: "standard", id: 273 },
  { name: "Bolto", category: "Pistol", type: "standard", id: 274 },
  { name: "Boltor", category: "Assault Rifle", type: "standard", id: 275 },
  { name: "Boltor Prime", category: "Assault Rifle", type: "prime", id: 276 },
  { name: "Brakk", category: "Pistol", type: "standard", id: 277 },
  { name: "Braton", category: "Assault Rifle", type: "standard", id: 278 },
  { name: "Braton Prime", category: "Assault Rifle", type: "prime", id: 279 },
  {
    name: "Braton Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 280,
  },
  { name: "Broken Scepter", category: "Staves", type: "standard", id: 281 },
  { name: "Broken War", category: "Swords", type: "standard", id: 282 },
  { name: "Bronco", category: "Pistol", type: "standard", id: 283 },
  { name: "Bronco Prime", category: "Pistol", type: "prime", id: 284 },
  { name: "Bubonico", category: "Shotgun", type: "standard", id: 285 },
  { name: "Burst Laser", category: "Pistol", type: "standard", id: 286 },
  { name: "Burst Laser Prime", category: "Pistol", type: "prime", id: 287 },
  { name: "Burston", category: "Assault Rifle", type: "standard", id: 288 },
  { name: "Burston Prime", category: "Assault Rifle", type: "prime", id: 289 },
  { name: "Buzlok", category: "Assault Rifle", type: "standard", id: 290 },
  { name: "Cadus", category: "Staves", type: "standard", id: 291 },
  { name: "Cantare", category: "Thrown", type: "standard", id: 292 },
  { name: "Carmine Penta", category: "Unique", type: "standard", id: 293 },
  { name: "Cassowar", category: "Polearms", type: "standard", id: 294 },
  { name: "Castanas", category: "Thrown", type: "standard", id: 295 },
  { name: "Catabolyst", category: "Pistol", type: "standard", id: 296 },
  { name: "Catchmoon", category: "Kitgun", type: "standard", id: 297 },
  { name: "Caustacyst", category: "Scythes", type: "standard", id: 298 },
  { name: "Cedo", category: "Shotgun", type: "standard", id: 299 },
  { name: "Centaur", category: "MELEE", type: "standard", id: 300 },
  { name: "Ceramic Dagger", category: "Daggers", type: "standard", id: 301 },
  { name: "Cerata", category: "Glaives", type: "standard", id: 302 },
  { name: "Cernos", category: "Bow", type: "standard", id: 303 },
  { name: "Cernos Prime", category: "Bow", type: "prime", id: 304 },
  { name: "Cestra", category: "Pistol", type: "standard", id: 305 },
  {
    name: "Ceti Lacera",
    category: "Blade And Whip",
    type: "standard",
    id: 306,
  },
  { name: "Cinta", category: "Bow", type: "standard", id: 307 },
  {
    name: "Cobra & Crane",
    category: "Sword And Shield",
    type: "standard",
    id: 308,
  },
  {
    name: "Cobra & Crane Prime",
    category: "Sword And Shield",
    type: "prime",
    id: 309,
  },
  { name: "Convectrix", category: "Shotgun", type: "standard", id: 310 },
  { name: "Corinth", category: "Shotgun", type: "standard", id: 311 },
  { name: "Corinth Prime", category: "Shotgun", type: "prime", id: 312 },
  { name: "Cortege", category: "Archgun", type: "standard", id: 313 },
  { name: "Corufell", category: "MELEE", type: "standard", id: 314 },
  { name: "Corvas", category: "Archgun", type: "standard", id: 315 },
  { name: "Corvas Prime", category: "Archgun", type: "prime", id: 316 },
  { name: "Cronus", category: "Swords", type: "standard", id: 317 },
  { name: "Cryotra", category: "SENTINEL WEAPON", type: "standard", id: 318 },
  { name: "Cyanex", category: "Pistol", type: "standard", id: 319 },
  { name: "Cyath", category: "Zaw", type: "standard", id: 320 },
  { name: "Cycron", category: "Pistol", type: "standard", id: 321 },
  { name: "Cyngas", category: "Archgun", type: "standard", id: 322 },
  { name: "Daikyu", category: "Bow", type: "standard", id: 323 },
  { name: "Dakra Prime", category: "Swords", type: "prime", id: 324 },
  { name: "Dark Dagger", category: "Daggers", type: "standard", id: 325 },
  {
    name: "Dark Split-Sword",
    category: "Dual Swords",
    type: "standard",
    id: 326,
  },
  { name: "Dark Sword", category: "Swords", type: "standard", id: 327 },
  { name: "Deconstructor", category: "MELEE", type: "standard", id: 328 },
  { name: "Deconstructor Prime", category: "MELEE", type: "prime", id: 329 },
  { name: "Dehtat", category: "Zaw", type: "standard", id: 330 },
  { name: "Dera", category: "Assault Rifle", type: "standard", id: 331 },
  { name: "Dera Vandal", category: "Assault Rifle", type: "standard", id: 332 },
  { name: "Desert Wind", category: "MELEE", type: "standard", id: 333 },
  { name: "Desert Wind Prime", category: "MELEE", type: "prime", id: 334 },
  { name: "Despair", category: "Thrown", type: "standard", id: 335 },
  { name: "Destreza", category: "Rapiers", type: "standard", id: 336 },
  { name: "Destreza Prime", category: "Rapiers", type: "prime", id: 337 },
  {
    name: "Deth Machine Rifle",
    category: "SENTINEL WEAPON",
    type: "standard",
    id: 338,
  },

  { name: "Detron", category: "Pistol", type: "standard", id: 339 },
  { name: "Dex Dakra", category: "Dual Swords", type: "standard", id: 340 },
  { name: "Dex Furis", category: "Pistol", type: "standard", id: 341 },
  { name: "Dex Nikana", category: "Nikanas", type: "standard", id: 342 },
  { name: "Dex Pixia", category: "Pistol", type: "standard", id: 343 },
  { name: "Dex Pixia Prime", category: "Pistol", type: "prime", id: 344 },
  { name: "Dex Sybaris", category: "Assault Rifle", type: "standard", id: 345 },
  { name: "Diwata", category: "MELEE", type: "standard", id: 346 },
  { name: "Diwata Prime", category: "MELEE", type: "prime", id: 347 },
  { name: "Dokrahm", category: "Zaw", type: "standard", id: 348 },
  { name: "Dorrclave", category: "Blade And Whip", type: "standard", id: 349 },
  { name: "Dragon Nikana", category: "Nikanas", type: "standard", id: 350 },
  { name: "Drakgoon", category: "Shotgun", type: "standard", id: 351 },
  { name: "Dread", category: "Bow", type: "standard", id: 352 },
  { name: "Dual Cestra", category: "Pistol", type: "standard", id: 353 },
  { name: "Dual Cleavers", category: "Dual Swords", type: "standard", id: 354 },
  { name: "Dual Decurion", category: "Archgun", type: "standard", id: 355 },
  { name: "Dual Ether", category: "Dual Swords", type: "standard", id: 356 },
  {
    name: "Dual Heat Swords",
    category: "Dual Swords",
    type: "standard",
    id: 357,
  },
  { name: "Dual Ichor", category: "Dual Swords", type: "standard", id: 358 },
  { name: "Dual Kamas", category: "Dual Swords", type: "standard", id: 359 },
  { name: "Dual Kamas Prime", category: "Dual Swords", type: "prime", id: 360 },
  { name: "Dual Keres", category: "Dual Swords", type: "standard", id: 361 },
  { name: "Dual Keres Prime", category: "Dual Swords", type: "prime", id: 362 },
  { name: "Dual Raza", category: "Dual Swords", type: "standard", id: 363 },
  { name: "Dual Skana", category: "Dual Swords", type: "standard", id: 364 },
  { name: "Dual Toxocyst", category: "Pistol", type: "standard", id: 365 },
  { name: "Dual Zoren", category: "Dual Swords", type: "standard", id: 366 },
  { name: "Edun", category: "Polearms", type: "standard", id: 367 },
  { name: "Ekhein", category: "Hammers", type: "standard", id: 368 },
  { name: "Embolist", category: "Pistol", type: "standard", id: 369 },
  { name: "Endura", category: "Rapiers", type: "standard", id: 370 },
  { name: "Epitaph", category: "Pistol", type: "standard", id: 371 },
  { name: "Epitaph Prime", category: "Pistol", type: "prime", id: 372 },
  {
    name: "Ether Daggers",
    category: "Dual Daggers",
    type: "standard",
    id: 373,
  },
  { name: "Ether Reaper", category: "Scythes", type: "standard", id: 374 },
  { name: "Ether Sword", category: "Swords", type: "standard", id: 375 },
  { name: "Euphona Prime", category: "Pistol", type: "prime", id: 376 },
  { name: "Evensong", category: "Bow", type: "standard", id: 377 },
  { name: "Exalted Blade", category: "MELEE", type: "standard", id: 378 },
  { name: "Exalted Prime Blade", category: "MELEE", type: "prime", id: 379 },
  { name: "Exalted Umbra Blade", category: "MELEE", type: "standard", id: 380 },
  { name: "Exergis", category: "Shotgun", type: "standard", id: 381 },
  { name: "Falcor", category: "Glaives", type: "standard", id: 382 },
  { name: "Fang", category: "Dual Daggers", type: "standard", id: 383 },
  { name: "Fang Prime", category: "Dual Daggers", type: "prime", id: 384 },
  { name: "Felarx", category: "Shotgun", type: "standard", id: 385 },
  { name: "Ferrox", category: "Speargun", type: "standard", id: 386 },
  { name: "Fluctus", category: "Archgun", type: "standard", id: 387 },
  { name: "Flux Rifle", category: "Assault Rifle", type: "standard", id: 388 },
  { name: "Fragor", category: "Hammers", type: "standard", id: 389 },
  { name: "Fragor Prime", category: "Hammers", type: "prime", id: 390 },
  { name: "Fulmin", category: "Assault Rifle", type: "standard", id: 391 },
  { name: "Fulmin Prime", category: "Assault Rifle", type: "prime", id: 392 },
  { name: "Furax", category: "Fists", type: "standard", id: 393 },
  { name: "Furax Wraith", category: "Fists", type: "standard", id: 394 },
  { name: "Furis", category: "Pistol", type: "standard", id: 395 },
  { name: "Fusilai", category: "Thrown", type: "standard", id: 396 },
  { name: "Galatine", category: "Heavy Blade", type: "standard", id: 397 },
  { name: "Galatine Prime", category: "Heavy Blade", type: "prime", id: 398 },
  { name: "Galvacord", category: "Whips", type: "standard", id: 399 },
  { name: "Gammacor", category: "Pistol", type: "standard", id: 400 },
  { name: "Garuda Prime Talons", category: "Claws", type: "prime", id: 401 },
  { name: "Garuda Talons", category: "Claws", type: "standard", id: 402 },
  { name: "Gazal Machete", category: "Machetes", type: "standard", id: 403 },
  { name: "Gaze", category: "Kitgun", type: "standard", id: 404 },
  { name: "Ghoulsaw", category: "MELEE", type: "standard", id: 405 },
  { name: "Glaive", category: "Glaives", type: "standard", id: 406 },
  { name: "Glaive Prime", category: "Glaives", type: "prime", id: 407 },
  { name: "Glaxion", category: "Assault Rifle", type: "standard", id: 408 },
  {
    name: "Glaxion Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 409,
  },
  { name: "Glory", category: "Pistol", type: "standard", id: 410 },
  { name: "Gorgon", category: "Assault Rifle", type: "standard", id: 411 },
  {
    name: "Gorgon Wraith",
    category: "Assault Rifle",
    type: "standard",
    id: 412,
  },
  { name: "Gotva Prime", category: "Assault Rifle", type: "prime", id: 413 },
  { name: "Grakata", category: "Assault Rifle", type: "standard", id: 414 },
  { name: "Gram", category: "Heavy Blade", type: "standard", id: 415 },
  { name: "Gram Prime", category: "Heavy Blade", type: "prime", id: 416 },
  { name: "Grattler", category: "Archgun", type: "standard", id: 417 },
  { name: "Grimoire", category: "Tome", type: "standard", id: 418 },
  { name: "Grinlok", category: "Assault Rifle", type: "standard", id: 419 },
  { name: "Guandao", category: "Polearms", type: "standard", id: 420 },
  { name: "Guandao Prime", category: "Polearms", type: "prime", id: 421 },
  { name: "Gunsen", category: "Warfans", type: "standard", id: 422 },
  { name: "Gunsen Prime", category: "Warfans", type: "prime", id: 423 },
  { name: "Halikar", category: "Glaives", type: "standard", id: 424 },
  { name: "Halikar Wraith", category: "Glaives", type: "standard", id: 425 },
  { name: "Harmony", category: "Scythes", type: "standard", id: 426 },
  { name: "Harpak", category: "Assault Rifle", type: "standard", id: 427 },
  { name: "Hate", category: "Scythes", type: "standard", id: 428 },
  { name: "Heat Dagger", category: "Daggers", type: "standard", id: 429 },
  { name: "Heat Sword", category: "Swords", type: "standard", id: 430 },
  { name: "Hek", category: "Shotgun", type: "standard", id: 431 },
  { name: "Heliocor", category: "Hammers", type: "standard", id: 432 },
  { name: "Helstrum", category: "SENTINEL WEAPON", type: "standard", id: 433 },
  { name: "Hema", category: "Assault Rifle", type: "standard", id: 434 },
  { name: "Hespar", category: "MELEE", type: "standard", id: 435 },
  { name: "Hikou", category: "Thrown", type: "standard", id: 436 },
  { name: "Hikou Prime", category: "Thrown", type: "prime", id: 437 },
  { name: "Hind", category: "Assault Rifle", type: "standard", id: 438 },
  { name: "Hirudo", category: "Sparring", type: "standard", id: 439 },
  { name: "Hystrix", category: "Pistol", type: "standard", id: 440 },
  { name: "Hystrix Prime", category: "Pistol", type: "prime", id: 441 },
  { name: "Ignis", category: "Unique", type: "standard", id: 442 },
  { name: "Ignis Wraith", category: "Unique", type: "standard", id: 443 },
  { name: "Imperator", category: "Archgun", type: "standard", id: 444 },
  { name: "Imperator Vandal", category: "Archgun", type: "standard", id: 445 },
  { name: "Innodem", category: "Daggers", type: "standard", id: 446 },
  { name: "Iron Staff", category: "MELEE", type: "standard", id: 447 },
  { name: "Iron Staff Prime", category: "MELEE", type: "prime", id: 448 },
  { name: "Ironbride", category: "MELEE", type: "standard", id: 449 },
  { name: "Jat Kittag", category: "Hammers", type: "standard", id: 450 },
  { name: "Jat Kusar", category: "Blade And Whip", type: "standard", id: 451 },
  { name: "Javlok", category: "Speargun", type: "standard", id: 452 },
  { name: "Jaw Sword", category: "Swords", type: "standard", id: 453 },
  { name: "Kama", category: "Machetes", type: "standard", id: 454 },
  { name: "Karak", category: "Assault Rifle", type: "standard", id: 455 },
  {
    name: "Karak Wraith",
    category: "Assault Rifle",
    type: "standard",
    id: 456,
  },
  { name: "Karyst", category: "Daggers", type: "standard", id: 457 },
  { name: "Karyst Prime", category: "Daggers", type: "prime", id: 458 },
  { name: "Kaszas", category: "MELEE", type: "standard", id: 459 },
  { name: "Keratinos", category: "Claws", type: "standard", id: 460 },
  { name: "Kesheg", category: "Polearms", type: "standard", id: 461 },
  { name: "Kestrel", category: "Glaives", type: "standard", id: 462 },
  { name: "Knell", category: "Pistol", type: "standard", id: 463 },
  { name: "Knell Prime", category: "Pistol", type: "prime", id: 464 },
  { name: "Knux", category: "MELEE", type: "standard", id: 465 },
  { name: "Kogake", category: "Sparring", type: "standard", id: 466 },
  { name: "Kogake Prime", category: "Sparring", type: "prime", id: 467 },
  { name: "Kohm", category: "Shotgun", type: "standard", id: 468 },
  { name: "Kohmak", category: "Pistol", type: "standard", id: 469 },
  { name: "Komorex", category: "Sniper", type: "standard", id: 470 },
  { name: "Kompressa", category: "Pistol", type: "standard", id: 471 },
  { name: "Korrudo", category: "Sparring", type: "standard", id: 472 },
  { name: "Korumm", category: "Polearms", type: "standard", id: 473 },
  { name: "Kraken", category: "Pistol", type: "standard", id: 474 },
  { name: "Kreska", category: "Machetes", type: "standard", id: 475 },
  { name: "Krohkur", category: "Swords", type: "standard", id: 476 },
  { name: "Kronen", category: "Tonfas", type: "standard", id: 477 },
  { name: "Kronen Prime", category: "Tonfas", type: "prime", id: 478 },
  { name: "Kronsh", category: "Zaw", type: "standard", id: 479 },
  { name: "Kulstar", category: "Pistol", type: "standard", id: 480 },
  { name: "Kunai", category: "Thrown", type: "standard", id: 481 },
  { name: "Kuva Ayanga", category: "Archgun", type: "standard", id: 482 },
  { name: "Kuva Brakk", category: "Pistol", type: "standard", id: 483 },
  { name: "Kuva Bramma", category: "Bow", type: "standard", id: 484 },
  {
    name: "Kuva Chakkhurr",
    category: "Assault Rifle",
    type: "standard",
    id: 485,
  },
  { name: "Kuva Drakgoon", category: "Shotgun", type: "standard", id: 486 },
  { name: "Kuva Grattler", category: "Archgun", type: "standard", id: 487 },
  { name: "Kuva Hek", category: "Shotgun", type: "standard", id: 488 },
  { name: "Kuva Hind", category: "Assault Rifle", type: "standard", id: 489 },
  { name: "Kuva Karak", category: "Assault Rifle", type: "standard", id: 490 },
  { name: "Kuva Kohm", category: "Shotgun", type: "standard", id: 491 },
  { name: "Kuva Kraken", category: "Pistol", type: "standard", id: 492 },
  { name: "Kuva Nukor", category: "Pistol", type: "standard", id: 493 },
  { name: "Kuva Ogris", category: "Unique", type: "standard", id: 494 },
  {
    name: "Kuva Quartakk",
    category: "Assault Rifle",
    type: "standard",
    id: 495,
  },
  { name: "Kuva Seer", category: "Pistol", type: "standard", id: 496 },
  { name: "Kuva Shildeg", category: "Hammers", type: "standard", id: 497 },
  { name: "Kuva Sobek", category: "Shotgun", type: "standard", id: 498 },
  { name: "Kuva Tonkor", category: "Unique", type: "standard", id: 499 },
  { name: "Kuva Twin Stubbas", category: "Pistol", type: "standard", id: 500 },
  { name: "Kuva Zarr", category: "Unique", type: "standard", id: 501 },
  { name: "Lacera", category: "Blade And Whip", type: "standard", id: 502 },
  { name: "Lacerten", category: "MELEE", type: "standard", id: 503 },
  { name: "Laetum", category: "Pistol", type: "standard", id: 504 },
  { name: "Lanka", category: "Sniper", type: "standard", id: 505 },
  { name: "Larkspur", category: "Archgun", type: "standard", id: 506 },
  { name: "Larkspur Prime", category: "Archgun", type: "prime", id: 507 },
  {
    name: "Laser Rifle",
    category: "SENTINEL WEAPON",
    type: "standard",
    id: 508,
  },
  { name: "Lato", category: "Pistol", type: "standard", id: 509 },
  { name: "Lato Prime", category: "Pistol", type: "prime", id: 510 },
  { name: "Lato Vandal", category: "Pistol", type: "standard", id: 511 },
  { name: "Latron", category: "Assault Rifle", type: "standard", id: 512 },
  { name: "Latron Prime", category: "Assault Rifle", type: "prime", id: 513 },
  {
    name: "Latron Wraith",
    category: "Assault Rifle",
    type: "standard",
    id: 514,
  },
  { name: "Lecta", category: "Whips", type: "standard", id: 515 },
  { name: "Lenz", category: "Bow", type: "standard", id: 516 },
  { name: "Lesion", category: "Polearms", type: "standard", id: 517 },
  { name: "Lex", category: "Pistol", type: "standard", id: 518 },
  { name: "Lex Prime", category: "Pistol", type: "prime", id: 519 },
  { name: "MK1-Bo", category: "Staves", type: "standard", id: 520 },
  { name: "MK1-Braton", category: "Assault Rifle", type: "standard", id: 521 },
  { name: "MK1-Furax", category: "Fists", type: "standard", id: 522 },
  { name: "MK1-Furis", category: "Pistol", type: "standard", id: 523 },
  { name: "MK1-Kunai", category: "Thrown", type: "standard", id: 524 },
  { name: "MK1-Paris", category: "Bow", type: "standard", id: 525 },
  { name: "MK1-Strun", category: "Shotgun", type: "standard", id: 526 },
  { name: "Machete", category: "Machetes", type: "standard", id: 527 },
  { name: "Machete Wraith", category: "Machetes", type: "standard", id: 528 },
  { name: "Magistar", category: "Hammers", type: "standard", id: 529 },
  { name: "Magnus", category: "Pistol", type: "standard", id: 530 },
  { name: "Magnus Prime", category: "Pistol", type: "prime", id: 531 },
  { name: "Mandonel", category: "Archgun", type: "standard", id: 532 },
  { name: "Mara Detron", category: "Pistol", type: "standard", id: 533 },
  { name: "Marelok", category: "Pistol", type: "standard", id: 534 },
  { name: "Masseter", category: "Heavy Blade", type: "standard", id: 535 },
  { name: "Masseter Prime", category: "Heavy Blade", type: "prime", id: 536 },
  { name: "Mausolon", category: "Archgun", type: "standard", id: 537 },
  { name: "Mewan", category: "Zaw", type: "standard", id: 538 },
  { name: "Mios", category: "Blade And Whip", type: "standard", id: 539 },
  { name: "Mire", category: "Swords", type: "standard", id: 540 },
  { name: "Miter", category: "Assault Rifle", type: "standard", id: 541 },
  { name: "Morgha", category: "Archgun", type: "standard", id: 542 },
  { name: "Multron", category: "SENTINEL WEAPON", type: "standard", id: 543 },
  { name: "Mutalist Cernos", category: "Bow", type: "standard", id: 544 },
  {
    name: "Mutalist Quanta",
    category: "Assault Rifle",
    type: "standard",
    id: 545,
  },
  { name: "Nagantaka", category: "Bow", type: "standard", id: 546 },
  { name: "Nagantaka Prime", category: "Bow", type: "prime", id: 547 },
  { name: "Nami Skyla", category: "Dual Swords", type: "standard", id: 548 },
  { name: "Nami Skyla Prime", category: "Dual Swords", type: "prime", id: 549 },
  { name: "Nami Solo", category: "Machetes", type: "standard", id: 550 },
  { name: "Nataruk", category: "Bow", type: "standard", id: 551 },
  { name: "Nepheri", category: "Dual Daggers", type: "standard", id: 552 },
  { name: "Nikana", category: "Nikanas", type: "standard", id: 553 },
  { name: "Nikana Prime", category: "Nikanas", type: "prime", id: 554 },
  { name: "Ninkondi", category: "Nunchaku", type: "standard", id: 555 },
  { name: "Ninkondi Prime", category: "Nunchaku", type: "prime", id: 556 },
  { name: "Noctua", category: "Tome", type: "standard", id: 557 },
  { name: "Nukor", category: "Pistol", type: "standard", id: 558 },
  { name: "Obex", category: "Sparring", type: "standard", id: 559 },
  { name: "Ocucor", category: "Pistol", type: "standard", id: 560 },
  { name: "Ogris", category: "Unique", type: "standard", id: 561 },
  { name: "Ohma", category: "Tonfas", type: "standard", id: 562 },
  { name: "Okina", category: "Dual Daggers", type: "standard", id: 563 },
  { name: "Okina Prime", category: "Dual Daggers", type: "prime", id: 564 },
  { name: "Onorix", category: "MELEE", type: "standard", id: 565 },
  { name: "Onos", category: "Pistol", type: "standard", id: 566 },
  { name: "Ooltha", category: "Zaw", type: "standard", id: 567 },
  { name: "Opticor", category: "Unique", type: "standard", id: 568 },
  { name: "Opticor Vandal", category: "Unique", type: "standard", id: 569 },
  { name: "Orthos", category: "Polearms", type: "standard", id: 570 },
  { name: "Orthos Prime", category: "Polearms", type: "prime", id: 571 },
  { name: "Orvius", category: "Glaives", type: "standard", id: 572 },
  { name: "Pandero", category: "Pistol", type: "standard", id: 573 },
  { name: "Pandero Prime", category: "Pistol", type: "prime", id: 574 },
  { name: "Pangolin Prime", category: "Swords", type: "prime", id: 575 },
  { name: "Pangolin Sword", category: "Swords", type: "standard", id: 576 },
  { name: "Panthera", category: "Assault Rifle", type: "standard", id: 577 },
  { name: "Panthera Prime", category: "Assault Rifle", type: "prime", id: 578 },
  { name: "Paracesis", category: "Heavy Blade", type: "standard", id: 579 },
  { name: "Paracyst", category: "Assault Rifle", type: "standard", id: 580 },
  { name: "Paris", category: "Bow", type: "standard", id: 581 },
  { name: "Paris Prime", category: "Bow", type: "prime", id: 582 },
  { name: "Pathocyst", category: "Glaives", type: "standard", id: 583 },
  { name: "Pennant", category: "Two-Handed Nikana", type: "standard", id: 584 },
  { name: "Penta", category: "Unique", type: "standard", id: 585 },
  { name: "Perigale", category: "Sniper", type: "standard", id: 586 },
  { name: "Phaedra", category: "Archgun", type: "standard", id: 587 },
  { name: "Phage", category: "Shotgun", type: "standard", id: 588 },
  { name: "Phantasma", category: "Shotgun", type: "standard", id: 589 },
  { name: "Phantasma Prime", category: "Shotgun", type: "prime", id: 590 },
  { name: "Phenmor", category: "Assault Rifle", type: "standard", id: 591 },
  { name: "Plague Keewar", category: "Zaw", type: "standard", id: 592 },
  { name: "Plague Kripath", category: "Zaw", type: "standard", id: 593 },
  { name: "Plasma Sword", category: "Swords", type: "standard", id: 594 },
  { name: "Plinx", category: "Pistol", type: "standard", id: 595 },
  { name: "Pox", category: "Thrown", type: "standard", id: 596 },
  { name: "Praedos", category: "Tonfas", type: "standard", id: 597 },
  {
    name: "Prime Laser Rifle",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 598,
  },
  { name: "Prisma Angstrum", category: "Pistol", type: "standard", id: 599 },
  { name: "Prisma Burst Laser", category: "Pistol", type: "standard", id: 600 },
  {
    name: "Prisma Dual Cleavers",
    category: "Dual Swords",
    type: "standard",
    id: 601,
  },
  {
    name: "Prisma Dual Decurions",
    category: "Archgun",
    type: "standard",
    id: 602,
  },
  {
    name: "Prisma Gorgon",
    category: "Assault Rifle",
    type: "standard",
    id: 603,
  },
  {
    name: "Prisma Grakata",
    category: "Assault Rifle",
    type: "standard",
    id: 604,
  },
  {
    name: "Prisma Grinlok",
    category: "Assault Rifle",
    type: "standard",
    id: 605,
  },
  { name: "Prisma Lenz", category: "Bow", type: "standard", id: 606 },
  { name: "Prisma Machete", category: "Machetes", type: "standard", id: 607 },
  { name: "Prisma Obex", category: "Sparring", type: "standard", id: 608 },
  { name: "Prisma Ohma", category: "Tonfas", type: "standard", id: 609 },
  { name: "Prisma Skana", category: "Swords", type: "standard", id: 610 },
  {
    name: "Prisma Tetra",
    category: "Assault Rifle",
    type: "standard",
    id: 611,
  },
  {
    name: "Prisma Twin Gremlins",
    category: "Pistol",
    type: "standard",
    id: 612,
  },
  { name: "Prisma Veritux", category: "MELEE", type: "standard", id: 613 },
  { name: "Proboscis Cernos", category: "Bow", type: "standard", id: 614 },
  { name: "Prova", category: "Machetes", type: "standard", id: 615 },
  { name: "Prova Vandal", category: "Machetes", type: "standard", id: 616 },
  { name: "Pulmonars", category: "Nunchaku", type: "standard", id: 617 },
  { name: "Pupacyst", category: "Polearms", type: "standard", id: 618 },
  { name: "Pyrana", category: "Pistol", type: "standard", id: 619 },
  { name: "Pyrana Prime", category: "Pistol", type: "prime", id: 620 },
  { name: "Quanta", category: "Assault Rifle", type: "standard", id: 621 },
  {
    name: "Quanta Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 622,
  },
  { name: "Quartakk", category: "Assault Rifle", type: "standard", id: 623 },
  { name: "Quassus", category: "Warfans", type: "standard", id: 624 },
  { name: "Quatz", category: "Pistol", type: "standard", id: 625 },
  { name: "Quellor", category: "Assault Rifle", type: "standard", id: 626 },
  { name: "Rabvee", category: "Zaw", type: "standard", id: 627 },
  { name: "Rakta Ballistica", category: "Pistol", type: "standard", id: 628 },
  { name: "Rakta Cernos", category: "Bow", type: "standard", id: 629 },
  { name: "Rakta Dark Dagger", category: "Daggers", type: "standard", id: 630 },
  { name: "Rathbone", category: "MELEE", type: "standard", id: 631 },
  { name: "Rattleguts", category: "Kitgun", type: "standard", id: 632 },
  { name: "Rauta", category: "Shotgun", type: "standard", id: 633 },
  { name: "Reaper Prime", category: "Scythes", type: "prime", id: 634 },
  { name: "Redeemer", category: "Gunblade", type: "standard", id: 635 },
  { name: "Redeemer Prime", category: "Gunblade", type: "prime", id: 636 },
  { name: "Regulators", category: "Pistol", type: "standard", id: 637 },
  { name: "Regulators Prime", category: "Pistol", type: "prime", id: 638 },
  { name: "Ripkas", category: "Claws", type: "standard", id: 639 },
  { name: "Rubico", category: "Sniper", type: "standard", id: 640 },
  { name: "Rubico Prime", category: "Sniper", type: "prime", id: 641 },
  { name: "Rumblejack", category: "Daggers", type: "standard", id: 642 },
  { name: "Ruvox", category: "Fists", type: "standard", id: 643 },
  { name: "Sampotes", category: "Hammers", type: "standard", id: 644 },
  { name: "Sancti Castanas", category: "Thrown", type: "standard", id: 645 },
  { name: "Sancti Magistar", category: "Hammers", type: "standard", id: 646 },
  { name: "Sancti Tigris", category: "Shotgun", type: "standard", id: 647 },
  { name: "Sarofang", category: "Heavy Blade", type: "standard", id: 648 },
  { name: "Sarpa", category: "Gunblade", type: "standard", id: 649 },
  { name: "Scindo", category: "Heavy Blade", type: "standard", id: 650 },
  { name: "Scindo Prime", category: "Heavy Blade", type: "prime", id: 651 },
  { name: "Scoliac", category: "Whips", type: "standard", id: 652 },
  { name: "Scourge", category: "Speargun", type: "standard", id: 653 },
  { name: "Scourge Prime", category: "Speargun", type: "prime", id: 654 },
  { name: "Secura Dual Cestra", category: "Pistol", type: "standard", id: 655 },
  { name: "Secura Lecta", category: "Whips", type: "standard", id: 656 },
  { name: "Secura Penta", category: "Unique", type: "standard", id: 657 },
  { name: "Seer", category: "Pistol", type: "standard", id: 658 },
  { name: "Sepfahn", category: "Zaw", type: "standard", id: 659 },
  { name: "Sepulcrum", category: "Pistol", type: "standard", id: 660 },
  { name: "Serro", category: "Polearms", type: "standard", id: 661 },
  { name: "Shadow Claws", category: "MELEE", type: "standard", id: 662 },
  { name: "Shadow Claws Prime", category: "MELEE", type: "prime", id: 663 },
  { name: "Shaku", category: "Nunchaku", type: "standard", id: 664 },
  { name: "Shedu", category: "Assault Rifle", type: "standard", id: 665 },
  { name: "Sheev", category: "Daggers", type: "standard", id: 666 },
  { name: "Sibear", category: "Hammers", type: "standard", id: 667 },
  { name: "Sicarus", category: "Pistol", type: "standard", id: 668 },
  { name: "Sicarus Prime", category: "Pistol", type: "prime", id: 669 },
  {
    name: "Sigma & Octantis",
    category: "Sword And Shield",
    type: "standard",
    id: 670,
  },
  {
    name: "Silva & Aegis",
    category: "Sword And Shield",
    type: "standard",
    id: 671,
  },
  {
    name: "Silva & Aegis Prime",
    category: "Sword And Shield",
    type: "prime",
    id: 672,
  },
  { name: "Simulor", category: "Assault Rifle", type: "standard", id: 673 },
  { name: "Skana", category: "Swords", type: "standard", id: 674 },
  { name: "Skana Prime", category: "Swords", type: "prime", id: 675 },
  { name: "Skiajati", category: "Nikanas", type: "standard", id: 676 },
  { name: "Slaytra", category: "Machetes", type: "standard", id: 677 },
  { name: "Snipetron", category: "Sniper", type: "standard", id: 678 },
  { name: "Snipetron Vandal", category: "Sniper", type: "standard", id: 679 },
  { name: "Sobek", category: "Shotgun", type: "standard", id: 680 },
  { name: "Soma", category: "Assault Rifle", type: "standard", id: 681 },
  { name: "Soma Prime", category: "Assault Rifle", type: "prime", id: 682 },
  { name: "Sonicor", category: "Pistol", type: "standard", id: 683 },
  { name: "Spectra", category: "Pistol", type: "standard", id: 684 },
  { name: "Spectra Vandal", category: "Pistol", type: "standard", id: 685 },
  { name: "Spira", category: "Thrown", type: "standard", id: 686 },
  { name: "Spira Prime", category: "Thrown", type: "prime", id: 687 },
  { name: "Sporelacer", category: "Kitgun", type: "standard", id: 688 },
  { name: "Sporothrix", category: "Sniper", type: "standard", id: 689 },
  { name: "Stahlta", category: "Assault Rifle", type: "standard", id: 690 },
  { name: "Staticor", category: "Pistol", type: "standard", id: 691 },
  { name: "Steflos", category: "Shotgun", type: "standard", id: 692 },
  { name: "Stinger", category: "SENTINEL WEAPON", type: "standard", id: 693 },
  { name: "Stradavar", category: "Assault Rifle", type: "standard", id: 694 },
  {
    name: "Stradavar Prime",
    category: "Assault Rifle",
    type: "prime",
    id: 695,
  },
  { name: "Stropha", category: "Gunblade", type: "standard", id: 696 },
  { name: "Strun", category: "Shotgun", type: "standard", id: 697 },
  { name: "Strun Prime", category: "Shotgun", type: "prime", id: 698 },
  { name: "Strun Wraith", category: "Shotgun", type: "standard", id: 699 },
  { name: "Stubba", category: "Pistol", type: "standard", id: 700 },
  { name: "Stug", category: "Pistol", type: "standard", id: 701 },
  { name: "Sun & Moon", category: "MELEE", type: "standard", id: 702 },
  { name: "Supra", category: "Assault Rifle", type: "standard", id: 703 },
  {
    name: "Supra Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 704,
  },
  { name: "Sweeper", category: "SENTINEL WEAPON", type: "standard", id: 705 },
  {
    name: "Sweeper Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 706,
  },
  { name: "Syam", category: "Nikanas", type: "standard", id: 707 },
  { name: "Sybaris", category: "Assault Rifle", type: "standard", id: 708 },
  { name: "Sybaris Prime", category: "Assault Rifle", type: "prime", id: 709 },
  { name: "Sydon", category: "Polearms", type: "standard", id: 710 },
  { name: "Synapse", category: "Assault Rifle", type: "standard", id: 711 },
  { name: "Synoid Gammacor", category: "Pistol", type: "standard", id: 712 },
  { name: "Synoid Heliocor", category: "Hammers", type: "standard", id: 713 },
  {
    name: "Synoid Simulor",
    category: "Assault Rifle",
    type: "standard",
    id: 714,
  },
  { name: "Talons", category: "Thrown", type: "standard", id: 715 },
  { name: "Tatsu", category: "Two-Handed Nikana", type: "standard", id: 716 },
  {
    name: "Tatsu Prime",
    category: "Two-Handed Nikana",
    type: "prime",
    id: 717,
  },
  { name: "Tazicor", category: "SENTINEL WEAPON", type: "standard", id: 718 },
  { name: "Tekko", category: "Fists", type: "standard", id: 719 },
  { name: "Tekko Prime", category: "Fists", type: "prime", id: 720 },
  { name: "Telos Akbolto", category: "Pistol", type: "standard", id: 721 },
  { name: "Telos Boltace", category: "Tonfas", type: "standard", id: 722 },
  {
    name: "Telos Boltor",
    category: "Assault Rifle",
    type: "standard",
    id: 723,
  },
  {
    name: "Tenet Agendus",
    category: "Sword And Shield",
    type: "standard",
    id: 724,
  },
  {
    name: "Tenet Arca Plasmor",
    category: "Shotgun",
    type: "standard",
    id: 725,
  },
  { name: "Tenet Cycron", category: "Pistol", type: "standard", id: 726 },
  { name: "Tenet Detron", category: "Pistol", type: "standard", id: 727 },
  { name: "Tenet Diplos", category: "Pistol", type: "standard", id: 728 },
  { name: "Tenet Envoy", category: "Unique", type: "standard", id: 729 },
  { name: "Tenet Exec", category: "Heavy Blade", type: "standard", id: 730 },
  { name: "Tenet Ferrox", category: "Speargun", type: "standard", id: 731 },
  {
    name: "Tenet Flux Rifle",
    category: "Assault Rifle",
    type: "standard",
    id: 732,
  },
  {
    name: "Tenet Glaxion",
    category: "Assault Rifle",
    type: "standard",
    id: 733,
  },
  { name: "Tenet Grigori", category: "Scythes", type: "standard", id: 734 },
  {
    name: "Tenet Livia",
    category: "Two-Handed Nikana",
    type: "standard",
    id: 735,
  },
  { name: "Tenet Plinx", category: "Pistol", type: "standard", id: 736 },
  { name: "Tenet Spirex", category: "Pistol", type: "standard", id: 737 },
  { name: "Tenet Tetra", category: "Assault Rifle", type: "standard", id: 738 },
  { name: "Tenora", category: "Assault Rifle", type: "standard", id: 739 },
  { name: "Tenora Prime", category: "Assault Rifle", type: "prime", id: 740 },
  { name: "Tetra", category: "Assault Rifle", type: "standard", id: 741 },
  { name: "Tiberon", category: "Assault Rifle", type: "standard", id: 742 },
  { name: "Tiberon Prime", category: "Assault Rifle", type: "prime", id: 743 },
  { name: "Tigris", category: "Shotgun", type: "standard", id: 744 },
  { name: "Tigris Prime", category: "Shotgun", type: "prime", id: 745 },
  { name: "Tipedo", category: "Staves", type: "standard", id: 746 },
  { name: "Tipedo Prime", category: "Staves", type: "prime", id: 747 },
  { name: "Tombfinger", category: "Kitgun", type: "standard", id: 748 },
  { name: "Tonbo", category: "Polearms", type: "standard", id: 749 },
  { name: "Tonkor", category: "Unique", type: "standard", id: 750 },
  { name: "Torid", category: "Unique", type: "standard", id: 751 },
  { name: "Trumna", category: "Assault Rifle", type: "standard", id: 752 },
  { name: "Twin Basolk", category: "Dual Swords", type: "standard", id: 753 },
  { name: "Twin Grakatas", category: "Pistol", type: "standard", id: 754 },
  { name: "Twin Gremlins", category: "Pistol", type: "standard", id: 755 },
  { name: "Twin Kohmak", category: "Pistol", type: "standard", id: 756 },
  { name: "Twin Krohkur", category: "Dual Swords", type: "standard", id: 757 },
  { name: "Twin Rogga", category: "Pistol", type: "standard", id: 758 },
  { name: "Twin Vipers", category: "Pistol", type: "standard", id: 759 },
  { name: "Twin Vipers Wraith", category: "Pistol", type: "standard", id: 760 },
  { name: "Tysis", category: "Pistol", type: "standard", id: 761 },
  { name: "Valkyr Prime Talons", category: "MELEE", type: "prime", id: 762 },
  { name: "Valkyr Talons", category: "MELEE", type: "standard", id: 763 },
  { name: "Vastilok", category: "Gunblade", type: "standard", id: 764 },
  { name: "Vasto", category: "Pistol", type: "standard", id: 765 },
  { name: "Vasto Prime", category: "Pistol", type: "prime", id: 766 },
  { name: "Vaykor Hek", category: "Shotgun", type: "standard", id: 767 },
  { name: "Vaykor Marelok", category: "Pistol", type: "standard", id: 768 },
  { name: "Vaykor Sydon", category: "Polearms", type: "standard", id: 769 },
  { name: "Vectis", category: "Sniper", type: "standard", id: 770 },
  { name: "Vectis Prime", category: "Sniper", type: "prime", id: 771 },
  { name: "Veldt", category: "Assault Rifle", type: "standard", id: 772 },
  { name: "Velocitus", category: "Archgun", type: "standard", id: 773 },
  { name: "Velox", category: "Pistol", type: "standard", id: 774 },
  { name: "Velox Prime", category: "Pistol", type: "prime", id: 775 },
  { name: "Venato", category: "Scythes", type: "standard", id: 776 },
  { name: "Venka", category: "Claws", type: "standard", id: 777 },
  { name: "Venka Prime", category: "Claws", type: "prime", id: 778 },
  { name: "Verdilac", category: "Whips", type: "standard", id: 779 },
  { name: "Verglas", category: "SENTINEL WEAPON", type: "standard", id: 780 },
  {
    name: "Verglas Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 781,
  },
  { name: "Vericres", category: "Warfans", type: "standard", id: 782 },
  { name: "Veritux", category: "MELEE", type: "standard", id: 783 },
  { name: "Vermisplicer", category: "Kitgun", type: "standard", id: 784 },
  { name: "Viper", category: "Pistol", type: "standard", id: 785 },
  { name: "Viper Wraith", category: "Pistol", type: "standard", id: 786 },
  { name: "Vitrica", category: "Heavy Blade", type: "standard", id: 787 },
  { name: "Volnus", category: "Hammers", type: "standard", id: 788 },
  { name: "Volnus Prime", category: "Hammers", type: "prime", id: 789 },
  { name: "Vulcax", category: "SENTINEL WEAPON", type: "standard", id: 790 },
  { name: "Vulkar", category: "Sniper", type: "standard", id: 791 },
  { name: "Vulkar Wraith", category: "Sniper", type: "standard", id: 792 },
  { name: "Vulklok", category: "SENTINEL WEAPON", type: "standard", id: 793 },
  { name: "War", category: "Heavy Blade", type: "standard", id: 794 },
  { name: "Wolf Sledge", category: "Hammers", type: "standard", id: 795 },
  { name: "Xoris", category: "Glaives", type: "standard", id: 796 },
  { name: "Zakti", category: "Pistol", type: "standard", id: 797 },
  { name: "Zakti Prime", category: "Pistol", type: "prime", id: 798 },
  { name: "Zarr", category: "Unique", type: "standard", id: 799 },
  { name: "Zenistar", category: "Heavy Blade", type: "standard", id: 800 },
  { name: "Zenith", category: "Assault Rifle", type: "standard", id: 801 },
  { name: "Zhuge", category: "Bow", type: "standard", id: 802 },
  { name: "Zhuge Prime", category: "Bow", type: "prime", id: 803 },
  { name: "Zylok", category: "Pistol", type: "standard", id: 804 },
  { name: "Zylok Prime", category: "Pistol", type: "prime", id: 805 },
  { name: "Zymos", category: "Pistol", type: "standard", id: 806 },
  {
    name: "Deth Machine Rifle Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 807,
  },
];
