type Weapon = {
  name: string;
  category: string;
  type: "prime" | "standard";
  id: number;
};

export const weaponList: Weapon[] = [
  { name: "AX-52", category: "Assault Rifle", type: "standard" },
  { name: "Acceltra", category: "Assault Rifle", type: "standard" },
  { name: "Acceltra Prime", category: "Assault Rifle", type: "prime" },
  { name: "Ack & Brunt", category: "Sword And Shield", type: "standard" },
  { name: "Acrid", category: "Pistol", type: "standard" },
  { name: "Aegrit", category: "Thrown", type: "standard" },
  { name: "Aeolak", category: "Assault Rifle", type: "standard" },
  { name: "Afentis", category: "Speargun", type: "standard" },
  { name: "Afuris", category: "Pistol", type: "standard" },
  { name: "Afuris Prime", category: "Pistol", type: "prime" },
  { name: "Agkuza", category: "MELEE", type: "standard" },
  { name: "Akarius", category: "Pistol", type: "standard" },
  { name: "Akarius Prime", category: "Pistol", type: "prime" },
  { name: "Akaten", category: "MELEE", type: "standard" },
  { name: "Akbolto", category: "Pistol", type: "standard" },
  { name: "Akbolto Prime", category: "Pistol", type: "prime" },
  { name: "Akbronco", category: "Pistol", type: "standard" },
  { name: "Akbronco Prime", category: "Pistol", type: "prime" },
  { name: "Akjagara", category: "Pistol", type: "standard" },
  { name: "Akjagara Prime", category: "Pistol", type: "prime" },
  { name: "Aklato", category: "Pistol", type: "standard" },
  { name: "Aklex", category: "Pistol", type: "standard" },
  { name: "Aklex Prime", category: "Pistol", type: "prime" },
  { name: "Akmagnus", category: "Pistol", type: "standard" },
  { name: "Akmagnus Prime", category: "Pistol", type: "prime" },
  { name: "Aksomati", category: "Pistol", type: "standard" },
  { name: "Aksomati Prime", category: "Pistol", type: "prime" },
  { name: "Akstiletto", category: "Pistol", type: "standard" },
  { name: "Akstiletto Prime", category: "Pistol", type: "prime" },
  { name: "Akvasto", category: "Pistol", type: "standard" },
  { name: "Akvasto Prime", category: "Pistol", type: "prime" },
  { name: "Akzani", category: "Pistol", type: "standard" },
  { name: "Alternox", category: "Assault Rifle", type: "standard" },
  { name: "Ambassador", category: "Assault Rifle", type: "standard" },
  { name: "Amphis", category: "Staves", type: "standard" },
  { name: "Amprex", category: "Assault Rifle", type: "standard" },
  { name: "Angstrum", category: "Pistol", type: "standard" },
  { name: "Anku", category: "Scythes", type: "standard" },
  { name: "Ankyros", category: "Fists", type: "standard" },
  { name: "Ankyros Prime", category: "Fists", type: "prime" },
  { name: "Arca Plasmor", category: "Shotgun", type: "standard" },
  { name: "Arca Scisco", category: "Pistol", type: "standard" },
  { name: "Arca Titron", category: "Hammers", type: "standard" },
  { name: "Argo & Vel", category: "Sword And Shield", type: "standard" },
  { name: "Argonak", category: "Assault Rifle", type: "standard" },
  { name: "Arquebex", category: "Archgun", type: "standard" },
  { name: "Artax", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Artemis Bow", category: "Bow", type: "standard" },
  { name: "Artemis Bow Prime", category: "Bow", type: "prime" },
  { name: "Arum Spinosa", category: "Warfans", type: "standard" },
  { name: "Astilla", category: "Shotgun", type: "standard" },
  { name: "Astilla Prime", category: "Shotgun", type: "prime" },
  { name: "Athodai", category: "Pistol", type: "standard" },
  { name: "Atomos", category: "Pistol", type: "standard" },
  { name: "Atterax", category: "Whips", type: "standard" },
  { name: "Attica", category: "Bow", type: "standard" },
  { name: "Azima", category: "Pistol", type: "standard" },
  { name: "Azothane", category: "Two-Handed Nikana", type: "standard" },
  { name: "Balefire Charger", category: "Pistol", type: "standard" },
  { name: "Balefire Charger Prime", category: "Pistol", type: "prime" },
  { name: "Balla", category: "Zaw", type: "standard" },
  { name: "Ballistica", category: "Pistol", type: "standard" },
  { name: "Ballistica Prime", category: "Pistol", type: "prime" },
  { name: "Basmu", category: "Assault Rifle", type: "standard" },
  { name: "Batoten", category: "MELEE", type: "standard" },
  { name: "Battacor", category: "Assault Rifle", type: "standard" },
  { name: "Baza", category: "Assault Rifle", type: "standard" },
  { name: "Baza Prime", category: "Assault Rifle", type: "prime" },
  { name: "Bo", category: "Staves", type: "standard" },
  { name: "Bo Prime", category: "Staves", type: "prime" },
  { name: "Boar", category: "Shotgun", type: "standard" },
  { name: "Boar Prime", category: "Shotgun", type: "prime" },
  { name: "Boltace", category: "Tonfas", type: "standard" },
  { name: "Bolto", category: "Pistol", type: "standard" },
  { name: "Boltor", category: "Assault Rifle", type: "standard" },
  { name: "Boltor Prime", category: "Assault Rifle", type: "prime" },
  { name: "Brakk", category: "Pistol", type: "standard" },
  { name: "Braton", category: "Assault Rifle", type: "standard" },
  { name: "Braton Prime", category: "Assault Rifle", type: "prime" },
  { name: "Braton Vandal", category: "Assault Rifle", type: "standard" },
  { name: "Broken Scepter", category: "Staves", type: "standard" },
  { name: "Broken War", category: "Swords", type: "standard" },
  { name: "Bronco", category: "Pistol", type: "standard" },
  { name: "Bronco Prime", category: "Pistol", type: "prime" },
  { name: "Bubonico", category: "Shotgun", type: "standard" },
  { name: "Burst Laser", category: "Pistol", type: "standard" },
  { name: "Burst Laser Prime", category: "Pistol", type: "prime" },
  { name: "Burston", category: "Assault Rifle", type: "standard" },
  { name: "Burston Prime", category: "Assault Rifle", type: "prime" },
  { name: "Buzlok", category: "Assault Rifle", type: "standard" },
  { name: "Cadus", category: "Staves", type: "standard" },
  { name: "Cantare", category: "Thrown", type: "standard" },
  { name: "Carmine Penta", category: "Unique", type: "standard" },
  { name: "Cassowar", category: "Polearms", type: "standard" },
  { name: "Castanas", category: "Thrown", type: "standard" },
  { name: "Catabolyst", category: "Pistol", type: "standard" },
  { name: "Catchmoon", category: "Kitgun", type: "standard" },
  { name: "Caustacyst", category: "Scythes", type: "standard" },
  { name: "Cedo", category: "Shotgun", type: "standard" },
  { name: "Centaur", category: "MELEE", type: "standard" },
  { name: "Ceramic Dagger", category: "Daggers", type: "standard" },
  { name: "Cerata", category: "Glaives", type: "standard" },
  { name: "Cernos", category: "Bow", type: "standard" },
  { name: "Cernos Prime", category: "Bow", type: "prime" },
  { name: "Cestra", category: "Pistol", type: "standard" },
  { name: "Ceti Lacera", category: "Blade And Whip", type: "standard" },
  { name: "Cinta", category: "Bow", type: "standard" },
  { name: "Cobra & Crane", category: "Sword And Shield", type: "standard" },
  { name: "Cobra & Crane Prime", category: "Sword And Shield", type: "prime" },
  { name: "Convectrix", category: "Shotgun", type: "standard" },
  { name: "Corinth", category: "Shotgun", type: "standard" },
  { name: "Corinth Prime", category: "Shotgun", type: "prime" },
  { name: "Cortege", category: "Archgun", type: "standard" },
  { name: "Corufell", category: "MELEE", type: "standard" },
  { name: "Corvas", category: "Archgun", type: "standard" },
  { name: "Corvas Prime", category: "Archgun", type: "prime" },
  { name: "Cronus", category: "Swords", type: "standard" },
  { name: "Cryotra", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Cyanex", category: "Pistol", type: "standard" },
  { name: "Cyath", category: "Zaw", type: "standard" },
  { name: "Cycron", category: "Pistol", type: "standard" },
  { name: "Cyngas", category: "Archgun", type: "standard" },
  { name: "Daikyu", category: "Bow", type: "standard" },
  { name: "Dakra Prime", category: "Swords", type: "prime" },
  { name: "Dark Dagger", category: "Daggers", type: "standard" },
  { name: "Dark Split-Sword", category: "Dual Swords", type: "standard" },
  { name: "Dark Sword", category: "Swords", type: "standard" },
  { name: "Deconstructor", category: "MELEE", type: "standard" },
  { name: "Deconstructor Prime", category: "MELEE", type: "prime" },
  { name: "Dehtat", category: "Zaw", type: "standard" },
  { name: "Dera", category: "Assault Rifle", type: "standard" },
  { name: "Dera Vandal", category: "Assault Rifle", type: "standard" },
  { name: "Desert Wind", category: "MELEE", type: "standard" },
  { name: "Desert Wind Prime", category: "MELEE", type: "prime" },
  { name: "Despair", category: "Thrown", type: "standard" },
  { name: "Destreza", category: "Rapiers", type: "standard" },
  { name: "Destreza Prime", category: "Rapiers", type: "prime" },
  { name: "Deth Machine Rifle", category: "SENTINEL WEAPON", type: "standard" },
  {
    name: "Deth Machine Rifle Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
  },
  { name: "Detron", category: "Pistol", type: "standard" },
  { name: "Dex Dakra", category: "Dual Swords", type: "standard" },
  { name: "Dex Furis", category: "Pistol", type: "standard" },
  { name: "Dex Nikana", category: "Nikanas", type: "standard" },
  { name: "Dex Pixia", category: "Pistol", type: "standard" },
  { name: "Dex Pixia Prime", category: "Pistol", type: "prime" },
  { name: "Dex Sybaris", category: "Assault Rifle", type: "standard" },
  { name: "Diwata", category: "MELEE", type: "standard" },
  { name: "Diwata Prime", category: "MELEE", type: "prime" },
  { name: "Dokrahm", category: "Zaw", type: "standard" },
  { name: "Dorrclave", category: "Blade And Whip", type: "standard" },
  { name: "Dragon Nikana", category: "Nikanas", type: "standard" },
  { name: "Drakgoon", category: "Shotgun", type: "standard" },
  { name: "Dread", category: "Bow", type: "standard" },
  { name: "Dual Cestra", category: "Pistol", type: "standard" },
  { name: "Dual Cleavers", category: "Dual Swords", type: "standard" },
  { name: "Dual Decurion", category: "Archgun", type: "standard" },
  { name: "Dual Ether", category: "Dual Swords", type: "standard" },
  { name: "Dual Heat Swords", category: "Dual Swords", type: "standard" },
  { name: "Dual Ichor", category: "Dual Swords", type: "standard" },
  { name: "Dual Kamas", category: "Dual Swords", type: "standard" },
  { name: "Dual Kamas Prime", category: "Dual Swords", type: "prime" },
  { name: "Dual Keres", category: "Dual Swords", type: "standard" },
  { name: "Dual Keres Prime", category: "Dual Swords", type: "prime" },
  { name: "Dual Raza", category: "Dual Swords", type: "standard" },
  { name: "Dual Skana", category: "Dual Swords", type: "standard" },
  { name: "Dual Toxocyst", category: "Pistol", type: "standard" },
  { name: "Dual Zoren", category: "Dual Swords", type: "standard" },
  { name: "Edun", category: "Polearms", type: "standard" },
  { name: "Ekhein", category: "Hammers", type: "standard" },
  { name: "Embolist", category: "Pistol", type: "standard" },
  { name: "Endura", category: "Rapiers", type: "standard" },
  { name: "Epitaph", category: "Pistol", type: "standard" },
  { name: "Epitaph Prime", category: "Pistol", type: "prime" },
  { name: "Ether Daggers", category: "Dual Daggers", type: "standard" },
  { name: "Ether Reaper", category: "Scythes", type: "standard" },
  { name: "Ether Sword", category: "Swords", type: "standard" },
  { name: "Euphona Prime", category: "Pistol", type: "prime" },
  { name: "Evensong", category: "Bow", type: "standard" },
  { name: "Exalted Blade", category: "MELEE", type: "standard" },
  { name: "Exalted Prime Blade", category: "MELEE", type: "prime" },
  { name: "Exalted Umbra Blade", category: "MELEE", type: "standard" },
  { name: "Exergis", category: "Shotgun", type: "standard" },
  { name: "Falcor", category: "Glaives", type: "standard" },
  { name: "Fang", category: "Dual Daggers", type: "standard" },
  { name: "Fang Prime", category: "Dual Daggers", type: "prime" },
  { name: "Felarx", category: "Shotgun", type: "standard" },
  { name: "Ferrox", category: "Speargun", type: "standard" },
  { name: "Fluctus", category: "Archgun", type: "standard" },
  { name: "Flux Rifle", category: "Assault Rifle", type: "standard" },
  { name: "Fragor", category: "Hammers", type: "standard" },
  { name: "Fragor Prime", category: "Hammers", type: "prime" },
  { name: "Fulmin", category: "Assault Rifle", type: "standard" },
  { name: "Fulmin Prime", category: "Assault Rifle", type: "prime" },
  { name: "Furax", category: "Fists", type: "standard" },
  { name: "Furax Wraith", category: "Fists", type: "standard" },
  { name: "Furis", category: "Pistol", type: "standard" },
  { name: "Fusilai", category: "Thrown", type: "standard" },
  { name: "Galatine", category: "Heavy Blade", type: "standard" },
  { name: "Galatine Prime", category: "Heavy Blade", type: "prime" },
  { name: "Galvacord", category: "Whips", type: "standard" },
  { name: "Gammacor", category: "Pistol", type: "standard" },
  { name: "Garuda Prime Talons", category: "Claws", type: "prime" },
  { name: "Garuda Talons", category: "Claws", type: "standard" },
  { name: "Gazal Machete", category: "Machetes", type: "standard" },
  { name: "Gaze", category: "Kitgun", type: "standard" },
  { name: "Ghoulsaw", category: "MELEE", type: "standard" },
  { name: "Glaive", category: "Glaives", type: "standard" },
  { name: "Glaive Prime", category: "Glaives", type: "prime" },
  { name: "Glaxion", category: "Assault Rifle", type: "standard" },
  { name: "Glaxion Vandal", category: "Assault Rifle", type: "standard" },
  { name: "Glory", category: "Pistol", type: "standard" },
  { name: "Gorgon", category: "Assault Rifle", type: "standard" },
  { name: "Gorgon Wraith", category: "Assault Rifle", type: "standard" },
  { name: "Gotva Prime", category: "Assault Rifle", type: "prime" },
  { name: "Grakata", category: "Assault Rifle", type: "standard" },
  { name: "Gram", category: "Heavy Blade", type: "standard" },
  { name: "Gram Prime", category: "Heavy Blade", type: "prime" },
  { name: "Grattler", category: "Archgun", type: "standard" },
  { name: "Grimoire", category: "Tome", type: "standard" },
  { name: "Grinlok", category: "Assault Rifle", type: "standard" },
  { name: "Guandao", category: "Polearms", type: "standard" },
  { name: "Guandao Prime", category: "Polearms", type: "prime" },
  { name: "Gunsen", category: "Warfans", type: "standard" },
  { name: "Gunsen Prime", category: "Warfans", type: "prime" },
  { name: "Halikar", category: "Glaives", type: "standard" },
  { name: "Halikar Wraith", category: "Glaives", type: "standard" },
  { name: "Harmony", category: "Scythes", type: "standard" },
  { name: "Harpak", category: "Assault Rifle", type: "standard" },
  { name: "Hate", category: "Scythes", type: "standard" },
  { name: "Heat Dagger", category: "Daggers", type: "standard" },
  { name: "Heat Sword", category: "Swords", type: "standard" },
  { name: "Hek", category: "Shotgun", type: "standard" },
  { name: "Heliocor", category: "Hammers", type: "standard" },
  { name: "Helstrum", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Hema", category: "Assault Rifle", type: "standard" },
  { name: "Hespar", category: "MELEE", type: "standard" },
  { name: "Hikou", category: "Thrown", type: "standard" },
  { name: "Hikou Prime", category: "Thrown", type: "prime" },
  { name: "Hind", category: "Assault Rifle", type: "standard" },
  { name: "Hirudo", category: "Sparring", type: "standard" },
  { name: "Hystrix", category: "Pistol", type: "standard" },
  { name: "Hystrix Prime", category: "Pistol", type: "prime" },
  { name: "Ignis", category: "Unique", type: "standard" },
  { name: "Ignis Wraith", category: "Unique", type: "standard" },
  { name: "Imperator", category: "Archgun", type: "standard" },
  { name: "Imperator Vandal", category: "Archgun", type: "standard" },
  { name: "Innodem", category: "Daggers", type: "standard" },
  { name: "Iron Staff", category: "MELEE", type: "standard" },
  { name: "Iron Staff Prime", category: "MELEE", type: "prime" },
  { name: "Ironbride", category: "MELEE", type: "standard" },
  { name: "Jat Kittag", category: "Hammers", type: "standard" },
  { name: "Jat Kusar", category: "Blade And Whip", type: "standard" },
  { name: "Javlok", category: "Speargun", type: "standard" },
  { name: "Jaw Sword", category: "Swords", type: "standard" },
  { name: "Kama", category: "Machetes", type: "standard" },
  { name: "Karak", category: "Assault Rifle", type: "standard" },
  { name: "Karak Wraith", category: "Assault Rifle", type: "standard" },
  { name: "Karyst", category: "Daggers", type: "standard" },
  { name: "Karyst Prime", category: "Daggers", type: "prime" },
  { name: "Kaszas", category: "MELEE", type: "standard" },
  { name: "Keratinos", category: "Claws", type: "standard" },
  { name: "Kesheg", category: "Polearms", type: "standard" },
  { name: "Kestrel", category: "Glaives", type: "standard" },
  { name: "Knell", category: "Pistol", type: "standard" },
  { name: "Knell Prime", category: "Pistol", type: "prime" },
  { name: "Knux", category: "MELEE", type: "standard" },
  { name: "Kogake", category: "Sparring", type: "standard" },
  { name: "Kogake Prime", category: "Sparring", type: "prime" },
  { name: "Kohm", category: "Shotgun", type: "standard" },
  { name: "Kohmak", category: "Pistol", type: "standard" },
  { name: "Komorex", category: "Sniper", type: "standard" },
  { name: "Kompressa", category: "Pistol", type: "standard" },
  { name: "Korrudo", category: "Sparring", type: "standard" },
  { name: "Korumm", category: "Polearms", type: "standard" },
  { name: "Kraken", category: "Pistol", type: "standard" },
  { name: "Kreska", category: "Machetes", type: "standard" },
  { name: "Krohkur", category: "Swords", type: "standard" },
  { name: "Kronen", category: "Tonfas", type: "standard" },
  { name: "Kronen Prime", category: "Tonfas", type: "prime" },
  { name: "Kronsh", category: "Zaw", type: "standard" },
  { name: "Kulstar", category: "Pistol", type: "standard" },
  { name: "Kunai", category: "Thrown", type: "standard" },
  { name: "Kuva Ayanga", category: "Archgun", type: "standard" },
  { name: "Kuva Brakk", category: "Pistol", type: "standard" },
  { name: "Kuva Bramma", category: "Bow", type: "standard" },
  { name: "Kuva Chakkhurr", category: "Assault Rifle", type: "standard" },
  { name: "Kuva Drakgoon", category: "Shotgun", type: "standard" },
  { name: "Kuva Grattler", category: "Archgun", type: "standard" },
  { name: "Kuva Hek", category: "Shotgun", type: "standard" },
  { name: "Kuva Hind", category: "Assault Rifle", type: "standard" },
  { name: "Kuva Karak", category: "Assault Rifle", type: "standard" },
  { name: "Kuva Kohm", category: "Shotgun", type: "standard" },
  { name: "Kuva Kraken", category: "Pistol", type: "standard" },
  { name: "Kuva Nukor", category: "Pistol", type: "standard" },
  { name: "Kuva Ogris", category: "Unique", type: "standard" },
  { name: "Kuva Quartakk", category: "Assault Rifle", type: "standard" },
  { name: "Kuva Seer", category: "Pistol", type: "standard" },
  { name: "Kuva Shildeg", category: "Hammers", type: "standard" },
  { name: "Kuva Sobek", category: "Shotgun", type: "standard" },
  { name: "Kuva Tonkor", category: "Unique", type: "standard" },
  { name: "Kuva Twin Stubbas", category: "Pistol", type: "standard" },
  { name: "Kuva Zarr", category: "Unique", type: "standard" },
  { name: "Lacera", category: "Blade And Whip", type: "standard" },
  { name: "Lacerten", category: "MELEE", type: "standard" },
  { name: "Laetum", category: "Pistol", type: "standard" },
  { name: "Lanka", category: "Sniper", type: "standard" },
  { name: "Larkspur", category: "Archgun", type: "standard" },
  { name: "Larkspur Prime", category: "Archgun", type: "prime" },
  { name: "Laser Rifle", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Lato", category: "Pistol", type: "standard" },
  { name: "Lato Prime", category: "Pistol", type: "prime" },
  { name: "Lato Vandal", category: "Pistol", type: "standard" },
  { name: "Latron", category: "Assault Rifle", type: "standard" },
  { name: "Latron Prime", category: "Assault Rifle", type: "prime" },
  { name: "Latron Wraith", category: "Assault Rifle", type: "standard" },
  { name: "Lecta", category: "Whips", type: "standard" },
  { name: "Lenz", category: "Bow", type: "standard" },
  { name: "Lesion", category: "Polearms", type: "standard" },
  { name: "Lex", category: "Pistol", type: "standard" },
  { name: "Lex Prime", category: "Pistol", type: "prime" },
  { name: "MK1-Bo", category: "Staves", type: "standard" },
  { name: "MK1-Braton", category: "Assault Rifle", type: "standard" },
  { name: "MK1-Furax", category: "Fists", type: "standard" },
  { name: "MK1-Furis", category: "Pistol", type: "standard" },
  { name: "MK1-Kunai", category: "Thrown", type: "standard" },
  { name: "MK1-Paris", category: "Bow", type: "standard" },
  { name: "MK1-Strun", category: "Shotgun", type: "standard" },
  { name: "Machete", category: "Machetes", type: "standard" },
  { name: "Machete Wraith", category: "Machetes", type: "standard" },
  { name: "Magistar", category: "Hammers", type: "standard" },
  { name: "Magnus", category: "Pistol", type: "standard" },
  { name: "Magnus Prime", category: "Pistol", type: "prime" },
  { name: "Mandonel", category: "Archgun", type: "standard" },
  { name: "Mara Detron", category: "Pistol", type: "standard" },
  { name: "Marelok", category: "Pistol", type: "standard" },
  { name: "Masseter", category: "Heavy Blade", type: "standard" },
  { name: "Masseter Prime", category: "Heavy Blade", type: "prime" },
  { name: "Mausolon", category: "Archgun", type: "standard" },
  { name: "Mewan", category: "Zaw", type: "standard" },
  { name: "Mios", category: "Blade And Whip", type: "standard" },
  { name: "Mire", category: "Swords", type: "standard" },
  { name: "Miter", category: "Assault Rifle", type: "standard" },
  { name: "Morgha", category: "Archgun", type: "standard" },
  { name: "Multron", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Mutalist Cernos", category: "Bow", type: "standard" },
  { name: "Mutalist Quanta", category: "Assault Rifle", type: "standard" },
  { name: "Nagantaka", category: "Bow", type: "standard" },
  { name: "Nagantaka Prime", category: "Bow", type: "prime" },
  { name: "Nami Skyla", category: "Dual Swords", type: "standard" },
  { name: "Nami Skyla Prime", category: "Dual Swords", type: "prime" },
  { name: "Nami Solo", category: "Machetes", type: "standard" },
  { name: "Nataruk", category: "Bow", type: "standard" },
  { name: "Nepheri", category: "Dual Daggers", type: "standard" },
  { name: "Nikana", category: "Nikanas", type: "standard" },
  { name: "Nikana Prime", category: "Nikanas", type: "prime" },
  { name: "Ninkondi", category: "Nunchaku", type: "standard" },
  { name: "Ninkondi Prime", category: "Nunchaku", type: "prime" },
  { name: "Noctua", category: "Tome", type: "standard" },
  { name: "Nukor", category: "Pistol", type: "standard" },
  { name: "Obex", category: "Sparring", type: "standard" },
  { name: "Ocucor", category: "Pistol", type: "standard" },
  { name: "Ogris", category: "Unique", type: "standard" },
  { name: "Ohma", category: "Tonfas", type: "standard" },
  { name: "Okina", category: "Dual Daggers", type: "standard" },
  { name: "Okina Prime", category: "Dual Daggers", type: "prime" },
  { name: "Onorix", category: "MELEE", type: "standard" },
  { name: "Onos", category: "Pistol", type: "standard" },
  { name: "Ooltha", category: "Zaw", type: "standard" },
  { name: "Opticor", category: "Unique", type: "standard" },
  { name: "Opticor Vandal", category: "Unique", type: "standard" },
  { name: "Orthos", category: "Polearms", type: "standard" },
  { name: "Orthos Prime", category: "Polearms", type: "prime" },
  { name: "Orvius", category: "Glaives", type: "standard" },
  { name: "Pandero", category: "Pistol", type: "standard" },
  { name: "Pandero Prime", category: "Pistol", type: "prime" },
  { name: "Pangolin Prime", category: "Swords", type: "prime" },
  { name: "Pangolin Sword", category: "Swords", type: "standard" },
  { name: "Panthera", category: "Assault Rifle", type: "standard" },
  { name: "Panthera Prime", category: "Assault Rifle", type: "prime" },
  { name: "Paracesis", category: "Heavy Blade", type: "standard" },
  { name: "Paracyst", category: "Assault Rifle", type: "standard" },
  { name: "Paris", category: "Bow", type: "standard" },
  { name: "Paris Prime", category: "Bow", type: "prime" },
  { name: "Pathocyst", category: "Glaives", type: "standard" },
  { name: "Pennant", category: "Two-Handed Nikana", type: "standard" },
  { name: "Penta", category: "Unique", type: "standard" },
  { name: "Perigale", category: "Sniper", type: "standard" },
  { name: "Phaedra", category: "Archgun", type: "standard" },
  { name: "Phage", category: "Shotgun", type: "standard" },
  { name: "Phantasma", category: "Shotgun", type: "standard" },
  { name: "Phantasma Prime", category: "Shotgun", type: "prime" },
  { name: "Phenmor", category: "Assault Rifle", type: "standard" },
  { name: "Plague Keewar", category: "Zaw", type: "standard" },
  { name: "Plague Kripath", category: "Zaw", type: "standard" },
  { name: "Plasma Sword", category: "Swords", type: "standard" },
  { name: "Plinx", category: "Pistol", type: "standard" },
  { name: "Pox", category: "Thrown", type: "standard" },
  { name: "Praedos", category: "Tonfas", type: "standard" },
  { name: "Prime Laser Rifle", category: "SENTINEL WEAPON", type: "prime" },
  { name: "Prisma Angstrum", category: "Pistol", type: "standard" },
  { name: "Prisma Burst Laser", category: "Pistol", type: "standard" },
  { name: "Prisma Dual Cleavers", category: "Dual Swords", type: "standard" },
  { name: "Prisma Dual Decurions", category: "Archgun", type: "standard" },
  { name: "Prisma Gorgon", category: "Assault Rifle", type: "standard" },
  { name: "Prisma Grakata", category: "Assault Rifle", type: "standard" },
  { name: "Prisma Grinlok", category: "Assault Rifle", type: "standard" },
  { name: "Prisma Lenz", category: "Bow", type: "standard" },
  { name: "Prisma Machete", category: "Machetes", type: "standard" },
  { name: "Prisma Obex", category: "Sparring", type: "standard" },
  { name: "Prisma Ohma", category: "Tonfas", type: "standard" },
  { name: "Prisma Skana", category: "Swords", type: "standard" },
  { name: "Prisma Tetra", category: "Assault Rifle", type: "standard" },
  { name: "Prisma Twin Gremlins", category: "Pistol", type: "standard" },
  { name: "Prisma Veritux", category: "MELEE", type: "standard" },
  { name: "Proboscis Cernos", category: "Bow", type: "standard" },
  { name: "Prova", category: "Machetes", type: "standard" },
  { name: "Prova Vandal", category: "Machetes", type: "standard" },
  { name: "Pulmonars", category: "Nunchaku", type: "standard" },
  { name: "Pupacyst", category: "Polearms", type: "standard" },
  { name: "Pyrana", category: "Pistol", type: "standard" },
  { name: "Pyrana Prime", category: "Pistol", type: "prime" },
  { name: "Quanta", category: "Assault Rifle", type: "standard" },
  { name: "Quanta Vandal", category: "Assault Rifle", type: "standard" },
  { name: "Quartakk", category: "Assault Rifle", type: "standard" },
  { name: "Quassus", category: "Warfans", type: "standard" },
  { name: "Quatz", category: "Pistol", type: "standard" },
  { name: "Quellor", category: "Assault Rifle", type: "standard" },
  { name: "Rabvee", category: "Zaw", type: "standard" },
  { name: "Rakta Ballistica", category: "Pistol", type: "standard" },
  { name: "Rakta Cernos", category: "Bow", type: "standard" },
  { name: "Rakta Dark Dagger", category: "Daggers", type: "standard" },
  { name: "Rathbone", category: "MELEE", type: "standard" },
  { name: "Rattleguts", category: "Kitgun", type: "standard" },
  { name: "Rauta", category: "Shotgun", type: "standard" },
  { name: "Reaper Prime", category: "Scythes", type: "prime" },
  { name: "Redeemer", category: "Gunblade", type: "standard" },
  { name: "Redeemer Prime", category: "Gunblade", type: "prime" },
  { name: "Regulators", category: "Pistol", type: "standard" },
  { name: "Regulators Prime", category: "Pistol", type: "prime" },
  { name: "Ripkas", category: "Claws", type: "standard" },
  { name: "Rubico", category: "Sniper", type: "standard" },
  { name: "Rubico Prime", category: "Sniper", type: "prime" },
  { name: "Rumblejack", category: "Daggers", type: "standard" },
  { name: "Ruvox", category: "Fists", type: "standard" },
  { name: "Sampotes", category: "Hammers", type: "standard" },
  { name: "Sancti Castanas", category: "Thrown", type: "standard" },
  { name: "Sancti Magistar", category: "Hammers", type: "standard" },
  { name: "Sancti Tigris", category: "Shotgun", type: "standard" },
  { name: "Sarofang", category: "Heavy Blade", type: "standard" },
  { name: "Sarpa", category: "Gunblade", type: "standard" },
  { name: "Scindo", category: "Heavy Blade", type: "standard" },
  { name: "Scindo Prime", category: "Heavy Blade", type: "prime" },
  { name: "Scoliac", category: "Whips", type: "standard" },
  { name: "Scourge", category: "Speargun", type: "standard" },
  { name: "Scourge Prime", category: "Speargun", type: "prime" },
  { name: "Secura Dual Cestra", category: "Pistol", type: "standard" },
  { name: "Secura Lecta", category: "Whips", type: "standard" },
  { name: "Secura Penta", category: "Unique", type: "standard" },
  { name: "Seer", category: "Pistol", type: "standard" },
  { name: "Sepfahn", category: "Zaw", type: "standard" },
  { name: "Sepulcrum", category: "Pistol", type: "standard" },
  { name: "Serro", category: "Polearms", type: "standard" },
  { name: "Shadow Claws", category: "MELEE", type: "standard" },
  { name: "Shadow Claws Prime", category: "MELEE", type: "prime" },
  { name: "Shaku", category: "Nunchaku", type: "standard" },
  { name: "Shedu", category: "Assault Rifle", type: "standard" },
  { name: "Sheev", category: "Daggers", type: "standard" },
  { name: "Sibear", category: "Hammers", type: "standard" },
  { name: "Sicarus", category: "Pistol", type: "standard" },
  { name: "Sicarus Prime", category: "Pistol", type: "prime" },
  { name: "Sigma & Octantis", category: "Sword And Shield", type: "standard" },
  { name: "Silva & Aegis", category: "Sword And Shield", type: "standard" },
  { name: "Silva & Aegis Prime", category: "Sword And Shield", type: "prime" },
  { name: "Simulor", category: "Assault Rifle", type: "standard" },
  { name: "Skana", category: "Swords", type: "standard" },
  { name: "Skana Prime", category: "Swords", type: "prime" },
  { name: "Skiajati", category: "Nikanas", type: "standard" },
  { name: "Slaytra", category: "Machetes", type: "standard" },
  { name: "Snipetron", category: "Sniper", type: "standard" },
  { name: "Snipetron Vandal", category: "Sniper", type: "standard" },
  { name: "Sobek", category: "Shotgun", type: "standard" },
  { name: "Soma", category: "Assault Rifle", type: "standard" },
  { name: "Soma Prime", category: "Assault Rifle", type: "prime" },
  { name: "Sonicor", category: "Pistol", type: "standard" },
  { name: "Spectra", category: "Pistol", type: "standard" },
  { name: "Spectra Vandal", category: "Pistol", type: "standard" },
  { name: "Spira", category: "Thrown", type: "standard" },
  { name: "Spira Prime", category: "Thrown", type: "prime" },
  { name: "Sporelacer", category: "Kitgun", type: "standard" },
  { name: "Sporothrix", category: "Sniper", type: "standard" },
  { name: "Stahlta", category: "Assault Rifle", type: "standard" },
  { name: "Staticor", category: "Pistol", type: "standard" },
  { name: "Steflos", category: "Shotgun", type: "standard" },
  { name: "Stinger", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Stradavar", category: "Assault Rifle", type: "standard" },
  { name: "Stradavar Prime", category: "Assault Rifle", type: "prime" },
  { name: "Stropha", category: "Gunblade", type: "standard" },
  { name: "Strun", category: "Shotgun", type: "standard" },
  { name: "Strun Prime", category: "Shotgun", type: "prime" },
  { name: "Strun Wraith", category: "Shotgun", type: "standard" },
  { name: "Stubba", category: "Pistol", type: "standard" },
  { name: "Stug", category: "Pistol", type: "standard" },
  { name: "Sun & Moon", category: "MELEE", type: "standard" },
  { name: "Supra", category: "Assault Rifle", type: "standard" },
  { name: "Supra Vandal", category: "Assault Rifle", type: "standard" },
  { name: "Sweeper", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Sweeper Prime", category: "SENTINEL WEAPON", type: "prime" },
  { name: "Syam", category: "Nikanas", type: "standard" },
  { name: "Sybaris", category: "Assault Rifle", type: "standard" },
  { name: "Sybaris Prime", category: "Assault Rifle", type: "prime" },
  { name: "Sydon", category: "Polearms", type: "standard" },
  { name: "Synapse", category: "Assault Rifle", type: "standard" },
  { name: "Synoid Gammacor", category: "Pistol", type: "standard" },
  { name: "Synoid Heliocor", category: "Hammers", type: "standard" },
  { name: "Synoid Simulor", category: "Assault Rifle", type: "standard" },
  { name: "Talons", category: "Thrown", type: "standard" },
  { name: "Tatsu", category: "Two-Handed Nikana", type: "standard" },
  { name: "Tatsu Prime", category: "Two-Handed Nikana", type: "prime" },
  { name: "Tazicor", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Tekko", category: "Fists", type: "standard" },
  { name: "Tekko Prime", category: "Fists", type: "prime" },
  { name: "Telos Akbolto", category: "Pistol", type: "standard" },
  { name: "Telos Boltace", category: "Tonfas", type: "standard" },
  { name: "Telos Boltor", category: "Assault Rifle", type: "standard" },
  { name: "Tenet Agendus", category: "Sword And Shield", type: "standard" },
  { name: "Tenet Arca Plasmor", category: "Shotgun", type: "standard" },
  { name: "Tenet Cycron", category: "Pistol", type: "standard" },
  { name: "Tenet Detron", category: "Pistol", type: "standard" },
  { name: "Tenet Diplos", category: "Pistol", type: "standard" },
  { name: "Tenet Envoy", category: "Unique", type: "standard" },
  { name: "Tenet Exec", category: "Heavy Blade", type: "standard" },
  { name: "Tenet Ferrox", category: "Speargun", type: "standard" },
  { name: "Tenet Flux Rifle", category: "Assault Rifle", type: "standard" },
  { name: "Tenet Glaxion", category: "Assault Rifle", type: "standard" },
  { name: "Tenet Grigori", category: "Scythes", type: "standard" },
  { name: "Tenet Livia", category: "Two-Handed Nikana", type: "standard" },
  { name: "Tenet Plinx", category: "Pistol", type: "standard" },
  { name: "Tenet Spirex", category: "Pistol", type: "standard" },
  { name: "Tenet Tetra", category: "Assault Rifle", type: "standard" },
  { name: "Tenora", category: "Assault Rifle", type: "standard" },
  { name: "Tenora Prime", category: "Assault Rifle", type: "prime" },
  { name: "Tetra", category: "Assault Rifle", type: "standard" },
  { name: "Tiberon", category: "Assault Rifle", type: "standard" },
  { name: "Tiberon Prime", category: "Assault Rifle", type: "prime" },
  { name: "Tigris", category: "Shotgun", type: "standard" },
  { name: "Tigris Prime", category: "Shotgun", type: "prime" },
  { name: "Tipedo", category: "Staves", type: "standard" },
  { name: "Tipedo Prime", category: "Staves", type: "prime" },
  { name: "Tombfinger", category: "Kitgun", type: "standard" },
  { name: "Tonbo", category: "Polearms", type: "standard" },
  { name: "Tonkor", category: "Unique", type: "standard" },
  { name: "Torid", category: "Unique", type: "standard" },
  { name: "Trumna", category: "Assault Rifle", type: "standard" },
  { name: "Twin Basolk", category: "Dual Swords", type: "standard" },
  { name: "Twin Grakatas", category: "Pistol", type: "standard" },
  { name: "Twin Gremlins", category: "Pistol", type: "standard" },
  { name: "Twin Kohmak", category: "Pistol", type: "standard" },
  { name: "Twin Krohkur", category: "Dual Swords", type: "standard" },
  { name: "Twin Rogga", category: "Pistol", type: "standard" },
  { name: "Twin Vipers", category: "Pistol", type: "standard" },
  { name: "Twin Vipers Wraith", category: "Pistol", type: "standard" },
  { name: "Tysis", category: "Pistol", type: "standard" },
  { name: "Valkyr Prime Talons", category: "MELEE", type: "prime" },
  { name: "Valkyr Talons", category: "MELEE", type: "standard" },
  { name: "Vastilok", category: "Gunblade", type: "standard" },
  { name: "Vasto", category: "Pistol", type: "standard" },
  { name: "Vasto Prime", category: "Pistol", type: "prime" },
  { name: "Vaykor Hek", category: "Shotgun", type: "standard" },
  { name: "Vaykor Marelok", category: "Pistol", type: "standard" },
  { name: "Vaykor Sydon", category: "Polearms", type: "standard" },
  { name: "Vectis", category: "Sniper", type: "standard" },
  { name: "Vectis Prime", category: "Sniper", type: "prime" },
  { name: "Veldt", category: "Assault Rifle", type: "standard" },
  { name: "Velocitus", category: "Archgun", type: "standard" },
  { name: "Velox", category: "Pistol", type: "standard" },
  { name: "Velox Prime", category: "Pistol", type: "prime" },
  { name: "Venato", category: "Scythes", type: "standard" },
  { name: "Venka", category: "Claws", type: "standard" },
  { name: "Venka Prime", category: "Claws", type: "prime" },
  { name: "Verdilac", category: "Whips", type: "standard" },
  { name: "Verglas", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Verglas Prime", category: "SENTINEL WEAPON", type: "prime" },
  { name: "Vericres", category: "Warfans", type: "standard" },
  { name: "Veritux", category: "MELEE", type: "standard" },
  { name: "Vermisplicer", category: "Kitgun", type: "standard" },
  { name: "Viper", category: "Pistol", type: "standard" },
  { name: "Viper Wraith", category: "Pistol", type: "standard" },
  { name: "Vitrica", category: "Heavy Blade", type: "standard" },
  { name: "Volnus", category: "Hammers", type: "standard" },
  { name: "Volnus Prime", category: "Hammers", type: "prime" },
  { name: "Vulcax", category: "SENTINEL WEAPON", type: "standard" },
  { name: "Vulkar", category: "Sniper", type: "standard" },
  { name: "Vulkar Wraith", category: "Sniper", type: "standard" },
  { name: "Vulklok", category: "SENTINEL WEAPON", type: "standard" },
  { name: "War", category: "Heavy Blade", type: "standard" },
  { name: "Wolf Sledge", category: "Hammers", type: "standard" },
  { name: "Xoris", category: "Glaives", type: "standard" },
  { name: "Zakti", category: "Pistol", type: "standard" },
  { name: "Zakti Prime", category: "Pistol", type: "prime" },
  { name: "Zarr", category: "Unique", type: "standard" },
  { name: "Zenistar", category: "Heavy Blade", type: "standard" },
  { name: "Zenith", category: "Assault Rifle", type: "standard" },
  { name: "Zhuge", category: "Bow", type: "standard" },
  { name: "Zhuge Prime", category: "Bow", type: "prime" },
  { name: "Zylok", category: "Pistol", type: "standard" },
  { name: "Zylok Prime", category: "Pistol", type: "prime" },
  { name: "Zymos", category: "Pistol", type: "standard" },
];
