type Weapon = {
  name: string;
  category: string;
  type: "prime" | "standard";
  id: number;
};

export const weaponList: Weapon[] = [
  { name: "AX-52", category: "Assault Rifle", type: "standard", id: 1 },
  { name: "Acceltra", category: "Assault Rifle", type: "standard", id: 2 },
  { name: "Acceltra Prime", category: "Assault Rifle", type: "prime", id: 3 },
  {
    name: "Ack & Brunt",
    category: "Sword And Shield",
    type: "standard",
    id: 4,
  },
  { name: "Acrid", category: "Pistol", type: "standard", id: 5 },
  { name: "Aegrit", category: "Thrown", type: "standard", id: 6 },
  { name: "Aeolak", category: "Assault Rifle", type: "standard", id: 7 },
  { name: "Afentis", category: "Speargun", type: "standard", id: 8 },
  { name: "Afuris", category: "Pistol", type: "standard", id: 9 },
  { name: "Afuris Prime", category: "Pistol", type: "prime", id: 10 },
  { name: "Agkuza", category: "MELEE", type: "standard", id: 11 },
  { name: "Akarius", category: "Pistol", type: "standard", id: 12 },
  { name: "Akarius Prime", category: "Pistol", type: "prime", id: 13 },
  { name: "Akaten", category: "MELEE", type: "standard", id: 14 },
  { name: "Akbolto", category: "Pistol", type: "standard", id: 15 },
  { name: "Akbolto Prime", category: "Pistol", type: "prime", id: 16 },
  { name: "Akbronco", category: "Pistol", type: "standard", id: 17 },
  { name: "Akbronco Prime", category: "Pistol", type: "prime", id: 18 },
  { name: "Akjagara", category: "Pistol", type: "standard", id: 19 },
  { name: "Akjagara Prime", category: "Pistol", type: "prime", id: 20 },
  { name: "Aklato", category: "Pistol", type: "standard", id: 21 },
  { name: "Aklex", category: "Pistol", type: "standard", id: 22 },
  { name: "Aklex Prime", category: "Pistol", type: "prime", id: 23 },
  { name: "Akmagnus", category: "Pistol", type: "standard", id: 24 },
  { name: "Akmagnus Prime", category: "Pistol", type: "prime", id: 25 },
  { name: "Aksomati", category: "Pistol", type: "standard", id: 26 },
  { name: "Aksomati Prime", category: "Pistol", type: "prime", id: 27 },
  { name: "Akstiletto", category: "Pistol", type: "standard", id: 28 },
  { name: "Akstiletto Prime", category: "Pistol", type: "prime", id: 29 },
  { name: "Akvasto", category: "Pistol", type: "standard", id: 30 },
  { name: "Akvasto Prime", category: "Pistol", type: "prime", id: 31 },
  { name: "Akzani", category: "Pistol", type: "standard", id: 32 },
  { name: "Alternox", category: "Assault Rifle", type: "standard", id: 33 },
  { name: "Ambassador", category: "Assault Rifle", type: "standard", id: 34 },
  { name: "Amphis", category: "Staves", type: "standard", id: 35 },
  { name: "Amprex", category: "Assault Rifle", type: "standard", id: 36 },
  { name: "Angstrum", category: "Pistol", type: "standard", id: 37 },
  { name: "Anku", category: "Scythes", type: "standard", id: 38 },
  { name: "Ankyros", category: "Fists", type: "standard", id: 39 },
  { name: "Ankyros Prime", category: "Fists", type: "prime", id: 40 },
  { name: "Arca Plasmor", category: "Shotgun", type: "standard", id: 41 },
  { name: "Arca Scisco", category: "Pistol", type: "standard", id: 42 },
  { name: "Arca Titron", category: "Hammers", type: "standard", id: 43 },
  {
    name: "Argo & Vel",
    category: "Sword And Shield",
    type: "standard",
    id: 44,
  },
  { name: "Argonak", category: "Assault Rifle", type: "standard", id: 45 },
  { name: "Arquebex", category: "Archgun", type: "standard", id: 46 },
  { name: "Artax", category: "SENTINEL WEAPON", type: "standard", id: 47 },
  { name: "Artemis Bow", category: "Bow", type: "standard", id: 48 },
  { name: "Artemis Bow Prime", category: "Bow", type: "prime", id: 49 },
  { name: "Arum Spinosa", category: "Warfans", type: "standard", id: 50 },
  { name: "Astilla", category: "Shotgun", type: "standard", id: 51 },
  { name: "Astilla Prime", category: "Shotgun", type: "prime", id: 52 },
  { name: "Athodai", category: "Pistol", type: "standard", id: 53 },
  { name: "Atomos", category: "Pistol", type: "standard", id: 54 },
  { name: "Atterax", category: "Whips", type: "standard", id: 55 },
  { name: "Attica", category: "Bow", type: "standard", id: 56 },
  { name: "Azima", category: "Pistol", type: "standard", id: 57 },
  { name: "Azothane", category: "Two-Handed Nikana", type: "standard", id: 58 },
  { name: "Balefire Charger", category: "Pistol", type: "standard", id: 59 },
  { name: "Balefire Charger Prime", category: "Pistol", type: "prime", id: 60 },
  { name: "Balla", category: "Zaw", type: "standard", id: 61 },
  { name: "Ballistica", category: "Pistol", type: "standard", id: 62 },
  { name: "Ballistica Prime", category: "Pistol", type: "prime", id: 63 },
  { name: "Basmu", category: "Assault Rifle", type: "standard", id: 64 },
  { name: "Batoten", category: "MELEE", type: "standard", id: 65 },
  { name: "Battacor", category: "Assault Rifle", type: "standard", id: 66 },
  { name: "Baza", category: "Assault Rifle", type: "standard", id: 67 },
  { name: "Baza Prime", category: "Assault Rifle", type: "prime", id: 68 },
  { name: "Bo", category: "Staves", type: "standard", id: 69 },
  { name: "Bo Prime", category: "Staves", type: "prime", id: 70 },
  { name: "Boar", category: "Shotgun", type: "standard", id: 71 },
  { name: "Boar Prime", category: "Shotgun", type: "prime", id: 72 },
  { name: "Boltace", category: "Tonfas", type: "standard", id: 73 },
  { name: "Bolto", category: "Pistol", type: "standard", id: 74 },
  { name: "Boltor", category: "Assault Rifle", type: "standard", id: 75 },
  { name: "Boltor Prime", category: "Assault Rifle", type: "prime", id: 76 },
  { name: "Brakk", category: "Pistol", type: "standard", id: 77 },
  { name: "Braton", category: "Assault Rifle", type: "standard", id: 78 },
  { name: "Braton Prime", category: "Assault Rifle", type: "prime", id: 79 },
  {
    name: "Braton Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 80,
  },
  { name: "Broken Scepter", category: "Staves", type: "standard", id: 81 },
  { name: "Broken War", category: "Swords", type: "standard", id: 82 },
  { name: "Bronco", category: "Pistol", type: "standard", id: 83 },
  { name: "Bronco Prime", category: "Pistol", type: "prime", id: 84 },
  { name: "Bubonico", category: "Shotgun", type: "standard", id: 85 },
  { name: "Burst Laser", category: "Pistol", type: "standard", id: 86 },
  { name: "Burst Laser Prime", category: "Pistol", type: "prime", id: 87 },
  { name: "Burston", category: "Assault Rifle", type: "standard", id: 88 },
  { name: "Burston Prime", category: "Assault Rifle", type: "prime", id: 89 },
  { name: "Buzlok", category: "Assault Rifle", type: "standard", id: 90 },
  { name: "Cadus", category: "Staves", type: "standard", id: 91 },
  { name: "Cantare", category: "Thrown", type: "standard", id: 92 },
  { name: "Carmine Penta", category: "Unique", type: "standard", id: 93 },
  { name: "Cassowar", category: "Polearms", type: "standard", id: 94 },
  { name: "Castanas", category: "Thrown", type: "standard", id: 95 },
  { name: "Catabolyst", category: "Pistol", type: "standard", id: 96 },
  { name: "Catchmoon", category: "Kitgun", type: "standard", id: 97 },
  { name: "Caustacyst", category: "Scythes", type: "standard", id: 98 },
  { name: "Cedo", category: "Shotgun", type: "standard", id: 99 },
  { name: "Centaur", category: "MELEE", type: "standard", id: 100 },
  { name: "Ceramic Dagger", category: "Daggers", type: "standard", id: 101 },
  { name: "Cerata", category: "Glaives", type: "standard", id: 102 },
  { name: "Cernos", category: "Bow", type: "standard", id: 103 },
  { name: "Cernos Prime", category: "Bow", type: "prime", id: 104 },
  { name: "Cestra", category: "Pistol", type: "standard", id: 105 },
  {
    name: "Ceti Lacera",
    category: "Blade And Whip",
    type: "standard",
    id: 106,
  },
  { name: "Cinta", category: "Bow", type: "standard", id: 107 },
  {
    name: "Cobra & Crane",
    category: "Sword And Shield",
    type: "standard",
    id: 108,
  },
  {
    name: "Cobra & Crane Prime",
    category: "Sword And Shield",
    type: "prime",
    id: 109,
  },
  { name: "Convectrix", category: "Shotgun", type: "standard", id: 110 },
  { name: "Corinth", category: "Shotgun", type: "standard", id: 111 },
  { name: "Corinth Prime", category: "Shotgun", type: "prime", id: 112 },
  { name: "Cortege", category: "Archgun", type: "standard", id: 113 },
  { name: "Corufell", category: "MELEE", type: "standard", id: 114 },
  { name: "Corvas", category: "Archgun", type: "standard", id: 115 },
  { name: "Corvas Prime", category: "Archgun", type: "prime", id: 116 },
  { name: "Cronus", category: "Swords", type: "standard", id: 117 },
  { name: "Cryotra", category: "SENTINEL WEAPON", type: "standard", id: 118 },
  { name: "Cyanex", category: "Pistol", type: "standard", id: 119 },
  { name: "Cyath", category: "Zaw", type: "standard", id: 120 },
  { name: "Cycron", category: "Pistol", type: "standard", id: 121 },
  { name: "Cyngas", category: "Archgun", type: "standard", id: 122 },
  { name: "Daikyu", category: "Bow", type: "standard", id: 123 },
  { name: "Dakra Prime", category: "Swords", type: "prime", id: 124 },
  { name: "Dark Dagger", category: "Daggers", type: "standard", id: 125 },
  {
    name: "Dark Split-Sword",
    category: "Dual Swords",
    type: "standard",
    id: 126,
  },
  { name: "Dark Sword", category: "Swords", type: "standard", id: 127 },
  { name: "Deconstructor", category: "MELEE", type: "standard", id: 128 },
  { name: "Deconstructor Prime", category: "MELEE", type: "prime", id: 129 },
  { name: "Dehtat", category: "Zaw", type: "standard", id: 130 },
  { name: "Dera", category: "Assault Rifle", type: "standard", id: 131 },
  { name: "Dera Vandal", category: "Assault Rifle", type: "standard", id: 132 },
  { name: "Desert Wind", category: "MELEE", type: "standard", id: 133 },
  { name: "Desert Wind Prime", category: "MELEE", type: "prime", id: 134 },
  { name: "Despair", category: "Thrown", type: "standard", id: 135 },
  { name: "Destreza", category: "Rapiers", type: "standard", id: 136 },
  { name: "Destreza Prime", category: "Rapiers", type: "prime", id: 137 },
  {
    name: "Deth Machine Rifle",
    category: "SENTINEL WEAPON",
    type: "standard",
    id: 138,
  },

  { name: "Detron", category: "Pistol", type: "standard", id: 139 },
  { name: "Dex Dakra", category: "Dual Swords", type: "standard", id: 140 },
  { name: "Dex Furis", category: "Pistol", type: "standard", id: 141 },
  { name: "Dex Nikana", category: "Nikanas", type: "standard", id: 142 },
  { name: "Dex Pixia", category: "Pistol", type: "standard", id: 143 },
  { name: "Dex Pixia Prime", category: "Pistol", type: "prime", id: 144 },
  { name: "Dex Sybaris", category: "Assault Rifle", type: "standard", id: 145 },
  { name: "Diwata", category: "MELEE", type: "standard", id: 146 },
  { name: "Diwata Prime", category: "MELEE", type: "prime", id: 147 },
  { name: "Dokrahm", category: "Zaw", type: "standard", id: 148 },
  { name: "Dorrclave", category: "Blade And Whip", type: "standard", id: 149 },
  { name: "Dragon Nikana", category: "Nikanas", type: "standard", id: 150 },
  { name: "Drakgoon", category: "Shotgun", type: "standard", id: 151 },
  { name: "Dread", category: "Bow", type: "standard", id: 152 },
  { name: "Dual Cestra", category: "Pistol", type: "standard", id: 153 },
  { name: "Dual Cleavers", category: "Dual Swords", type: "standard", id: 154 },
  { name: "Dual Decurion", category: "Archgun", type: "standard", id: 155 },
  { name: "Dual Ether", category: "Dual Swords", type: "standard", id: 156 },
  {
    name: "Dual Heat Swords",
    category: "Dual Swords",
    type: "standard",
    id: 157,
  },
  { name: "Dual Ichor", category: "Dual Swords", type: "standard", id: 158 },
  { name: "Dual Kamas", category: "Dual Swords", type: "standard", id: 159 },
  { name: "Dual Kamas Prime", category: "Dual Swords", type: "prime", id: 160 },
  { name: "Dual Keres", category: "Dual Swords", type: "standard", id: 161 },
  { name: "Dual Keres Prime", category: "Dual Swords", type: "prime", id: 162 },
  { name: "Dual Raza", category: "Dual Swords", type: "standard", id: 163 },
  { name: "Dual Skana", category: "Dual Swords", type: "standard", id: 164 },
  { name: "Dual Toxocyst", category: "Pistol", type: "standard", id: 165 },
  { name: "Dual Zoren", category: "Dual Swords", type: "standard", id: 166 },
  { name: "Edun", category: "Polearms", type: "standard", id: 167 },
  { name: "Ekhein", category: "Hammers", type: "standard", id: 168 },
  { name: "Embolist", category: "Pistol", type: "standard", id: 169 },
  { name: "Endura", category: "Rapiers", type: "standard", id: 170 },
  { name: "Epitaph", category: "Pistol", type: "standard", id: 171 },
  { name: "Epitaph Prime", category: "Pistol", type: "prime", id: 172 },
  {
    name: "Ether Daggers",
    category: "Dual Daggers",
    type: "standard",
    id: 173,
  },
  { name: "Ether Reaper", category: "Scythes", type: "standard", id: 174 },
  { name: "Ether Sword", category: "Swords", type: "standard", id: 175 },
  { name: "Euphona Prime", category: "Pistol", type: "prime", id: 176 },
  { name: "Evensong", category: "Bow", type: "standard", id: 177 },
  { name: "Exalted Blade", category: "MELEE", type: "standard", id: 178 },
  { name: "Exalted Prime Blade", category: "MELEE", type: "prime", id: 179 },
  { name: "Exalted Umbra Blade", category: "MELEE", type: "standard", id: 180 },
  { name: "Exergis", category: "Shotgun", type: "standard", id: 181 },
  { name: "Falcor", category: "Glaives", type: "standard", id: 182 },
  { name: "Fang", category: "Dual Daggers", type: "standard", id: 183 },
  { name: "Fang Prime", category: "Dual Daggers", type: "prime", id: 184 },
  { name: "Felarx", category: "Shotgun", type: "standard", id: 185 },
  { name: "Ferrox", category: "Speargun", type: "standard", id: 186 },
  { name: "Fluctus", category: "Archgun", type: "standard", id: 187 },
  { name: "Flux Rifle", category: "Assault Rifle", type: "standard", id: 188 },
  { name: "Fragor", category: "Hammers", type: "standard", id: 189 },
  { name: "Fragor Prime", category: "Hammers", type: "prime", id: 190 },
  { name: "Fulmin", category: "Assault Rifle", type: "standard", id: 191 },
  { name: "Fulmin Prime", category: "Assault Rifle", type: "prime", id: 192 },
  { name: "Furax", category: "Fists", type: "standard", id: 193 },
  { name: "Furax Wraith", category: "Fists", type: "standard", id: 194 },
  { name: "Furis", category: "Pistol", type: "standard", id: 195 },
  { name: "Fusilai", category: "Thrown", type: "standard", id: 196 },
  { name: "Galatine", category: "Heavy Blade", type: "standard", id: 197 },
  { name: "Galatine Prime", category: "Heavy Blade", type: "prime", id: 198 },
  { name: "Galvacord", category: "Whips", type: "standard", id: 199 },
  { name: "Gammacor", category: "Pistol", type: "standard", id: 200 },
  { name: "Garuda Prime Talons", category: "Claws", type: "prime", id: 201 },
  { name: "Garuda Talons", category: "Claws", type: "standard", id: 202 },
  { name: "Gazal Machete", category: "Machetes", type: "standard", id: 203 },
  { name: "Gaze", category: "Kitgun", type: "standard", id: 204 },
  { name: "Ghoulsaw", category: "MELEE", type: "standard", id: 205 },
  { name: "Glaive", category: "Glaives", type: "standard", id: 206 },
  { name: "Glaive Prime", category: "Glaives", type: "prime", id: 207 },
  { name: "Glaxion", category: "Assault Rifle", type: "standard", id: 208 },
  {
    name: "Glaxion Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 209,
  },
  { name: "Glory", category: "Pistol", type: "standard", id: 210 },
  { name: "Gorgon", category: "Assault Rifle", type: "standard", id: 211 },
  {
    name: "Gorgon Wraith",
    category: "Assault Rifle",
    type: "standard",
    id: 212,
  },
  { name: "Gotva Prime", category: "Assault Rifle", type: "prime", id: 213 },
  { name: "Grakata", category: "Assault Rifle", type: "standard", id: 214 },
  { name: "Gram", category: "Heavy Blade", type: "standard", id: 215 },
  { name: "Gram Prime", category: "Heavy Blade", type: "prime", id: 216 },
  { name: "Grattler", category: "Archgun", type: "standard", id: 217 },
  { name: "Grimoire", category: "Tome", type: "standard", id: 218 },
  { name: "Grinlok", category: "Assault Rifle", type: "standard", id: 219 },
  { name: "Guandao", category: "Polearms", type: "standard", id: 220 },
  { name: "Guandao Prime", category: "Polearms", type: "prime", id: 221 },
  { name: "Gunsen", category: "Warfans", type: "standard", id: 222 },
  { name: "Gunsen Prime", category: "Warfans", type: "prime", id: 223 },
  { name: "Halikar", category: "Glaives", type: "standard", id: 224 },
  { name: "Halikar Wraith", category: "Glaives", type: "standard", id: 225 },
  { name: "Harmony", category: "Scythes", type: "standard", id: 226 },
  { name: "Harpak", category: "Assault Rifle", type: "standard", id: 227 },
  { name: "Hate", category: "Scythes", type: "standard", id: 228 },
  { name: "Heat Dagger", category: "Daggers", type: "standard", id: 229 },
  { name: "Heat Sword", category: "Swords", type: "standard", id: 230 },
  { name: "Hek", category: "Shotgun", type: "standard", id: 231 },
  { name: "Heliocor", category: "Hammers", type: "standard", id: 232 },
  { name: "Helstrum", category: "SENTINEL WEAPON", type: "standard", id: 233 },
  { name: "Hema", category: "Assault Rifle", type: "standard", id: 234 },
  { name: "Hespar", category: "MELEE", type: "standard", id: 235 },
  { name: "Hikou", category: "Thrown", type: "standard", id: 236 },
  { name: "Hikou Prime", category: "Thrown", type: "prime", id: 237 },
  { name: "Hind", category: "Assault Rifle", type: "standard", id: 238 },
  { name: "Hirudo", category: "Sparring", type: "standard", id: 239 },
  { name: "Hystrix", category: "Pistol", type: "standard", id: 240 },
  { name: "Hystrix Prime", category: "Pistol", type: "prime", id: 241 },
  { name: "Ignis", category: "Unique", type: "standard", id: 242 },
  { name: "Ignis Wraith", category: "Unique", type: "standard", id: 243 },
  { name: "Imperator", category: "Archgun", type: "standard", id: 244 },
  { name: "Imperator Vandal", category: "Archgun", type: "standard", id: 245 },
  { name: "Innodem", category: "Daggers", type: "standard", id: 246 },
  { name: "Iron Staff", category: "MELEE", type: "standard", id: 247 },
  { name: "Iron Staff Prime", category: "MELEE", type: "prime", id: 248 },
  { name: "Ironbride", category: "MELEE", type: "standard", id: 249 },
  { name: "Jat Kittag", category: "Hammers", type: "standard", id: 250 },
  { name: "Jat Kusar", category: "Blade And Whip", type: "standard", id: 251 },
  { name: "Javlok", category: "Speargun", type: "standard", id: 252 },
  { name: "Jaw Sword", category: "Swords", type: "standard", id: 253 },
  { name: "Kama", category: "Machetes", type: "standard", id: 254 },
  { name: "Karak", category: "Assault Rifle", type: "standard", id: 255 },
  {
    name: "Karak Wraith",
    category: "Assault Rifle",
    type: "standard",
    id: 256,
  },
  { name: "Karyst", category: "Daggers", type: "standard", id: 257 },
  { name: "Karyst Prime", category: "Daggers", type: "prime", id: 258 },
  { name: "Kaszas", category: "MELEE", type: "standard", id: 259 },
  { name: "Keratinos", category: "Claws", type: "standard", id: 260 },
  { name: "Kesheg", category: "Polearms", type: "standard", id: 261 },
  { name: "Kestrel", category: "Glaives", type: "standard", id: 262 },
  { name: "Knell", category: "Pistol", type: "standard", id: 263 },
  { name: "Knell Prime", category: "Pistol", type: "prime", id: 264 },
  { name: "Knux", category: "MELEE", type: "standard", id: 265 },
  { name: "Kogake", category: "Sparring", type: "standard", id: 266 },
  { name: "Kogake Prime", category: "Sparring", type: "prime", id: 267 },
  { name: "Kohm", category: "Shotgun", type: "standard", id: 268 },
  { name: "Kohmak", category: "Pistol", type: "standard", id: 269 },
  { name: "Komorex", category: "Sniper", type: "standard", id: 270 },
  { name: "Kompressa", category: "Pistol", type: "standard", id: 271 },
  { name: "Korrudo", category: "Sparring", type: "standard", id: 272 },
  { name: "Korumm", category: "Polearms", type: "standard", id: 273 },
  { name: "Kraken", category: "Pistol", type: "standard", id: 274 },
  { name: "Kreska", category: "Machetes", type: "standard", id: 275 },
  { name: "Krohkur", category: "Swords", type: "standard", id: 276 },
  { name: "Kronen", category: "Tonfas", type: "standard", id: 277 },
  { name: "Kronen Prime", category: "Tonfas", type: "prime", id: 278 },
  { name: "Kronsh", category: "Zaw", type: "standard", id: 279 },
  { name: "Kulstar", category: "Pistol", type: "standard", id: 280 },
  { name: "Kunai", category: "Thrown", type: "standard", id: 281 },
  { name: "Kuva Ayanga", category: "Archgun", type: "standard", id: 282 },
  { name: "Kuva Brakk", category: "Pistol", type: "standard", id: 283 },
  { name: "Kuva Bramma", category: "Bow", type: "standard", id: 284 },
  {
    name: "Kuva Chakkhurr",
    category: "Assault Rifle",
    type: "standard",
    id: 285,
  },
  { name: "Kuva Drakgoon", category: "Shotgun", type: "standard", id: 286 },
  { name: "Kuva Grattler", category: "Archgun", type: "standard", id: 287 },
  { name: "Kuva Hek", category: "Shotgun", type: "standard", id: 288 },
  { name: "Kuva Hind", category: "Assault Rifle", type: "standard", id: 289 },
  { name: "Kuva Karak", category: "Assault Rifle", type: "standard", id: 290 },
  { name: "Kuva Kohm", category: "Shotgun", type: "standard", id: 291 },
  { name: "Kuva Kraken", category: "Pistol", type: "standard", id: 292 },
  { name: "Kuva Nukor", category: "Pistol", type: "standard", id: 293 },
  { name: "Kuva Ogris", category: "Unique", type: "standard", id: 294 },
  {
    name: "Kuva Quartakk",
    category: "Assault Rifle",
    type: "standard",
    id: 295,
  },
  { name: "Kuva Seer", category: "Pistol", type: "standard", id: 296 },
  { name: "Kuva Shildeg", category: "Hammers", type: "standard", id: 297 },
  { name: "Kuva Sobek", category: "Shotgun", type: "standard", id: 298 },
  { name: "Kuva Tonkor", category: "Unique", type: "standard", id: 299 },
  { name: "Kuva Twin Stubbas", category: "Pistol", type: "standard", id: 300 },
  { name: "Kuva Zarr", category: "Unique", type: "standard", id: 301 },
  { name: "Lacera", category: "Blade And Whip", type: "standard", id: 302 },
  { name: "Lacerten", category: "MELEE", type: "standard", id: 303 },
  { name: "Laetum", category: "Pistol", type: "standard", id: 304 },
  { name: "Lanka", category: "Sniper", type: "standard", id: 305 },
  { name: "Larkspur", category: "Archgun", type: "standard", id: 306 },
  { name: "Larkspur Prime", category: "Archgun", type: "prime", id: 307 },
  {
    name: "Laser Rifle",
    category: "SENTINEL WEAPON",
    type: "standard",
    id: 308,
  },
  { name: "Lato", category: "Pistol", type: "standard", id: 309 },
  { name: "Lato Prime", category: "Pistol", type: "prime", id: 310 },
  { name: "Lato Vandal", category: "Pistol", type: "standard", id: 311 },
  { name: "Latron", category: "Assault Rifle", type: "standard", id: 312 },
  { name: "Latron Prime", category: "Assault Rifle", type: "prime", id: 313 },
  {
    name: "Latron Wraith",
    category: "Assault Rifle",
    type: "standard",
    id: 314,
  },
  { name: "Lecta", category: "Whips", type: "standard", id: 315 },
  { name: "Lenz", category: "Bow", type: "standard", id: 316 },
  { name: "Lesion", category: "Polearms", type: "standard", id: 317 },
  { name: "Lex", category: "Pistol", type: "standard", id: 318 },
  { name: "Lex Prime", category: "Pistol", type: "prime", id: 319 },
  { name: "MK1-Bo", category: "Staves", type: "standard", id: 320 },
  { name: "MK1-Braton", category: "Assault Rifle", type: "standard", id: 321 },
  { name: "MK1-Furax", category: "Fists", type: "standard", id: 322 },
  { name: "MK1-Furis", category: "Pistol", type: "standard", id: 323 },
  { name: "MK1-Kunai", category: "Thrown", type: "standard", id: 324 },
  { name: "MK1-Paris", category: "Bow", type: "standard", id: 325 },
  { name: "MK1-Strun", category: "Shotgun", type: "standard", id: 326 },
  { name: "Machete", category: "Machetes", type: "standard", id: 327 },
  { name: "Machete Wraith", category: "Machetes", type: "standard", id: 328 },
  { name: "Magistar", category: "Hammers", type: "standard", id: 329 },
  { name: "Magnus", category: "Pistol", type: "standard", id: 330 },
  { name: "Magnus Prime", category: "Pistol", type: "prime", id: 331 },
  { name: "Mandonel", category: "Archgun", type: "standard", id: 332 },
  { name: "Mara Detron", category: "Pistol", type: "standard", id: 333 },
  { name: "Marelok", category: "Pistol", type: "standard", id: 334 },
  { name: "Masseter", category: "Heavy Blade", type: "standard", id: 335 },
  { name: "Masseter Prime", category: "Heavy Blade", type: "prime", id: 336 },
  { name: "Mausolon", category: "Archgun", type: "standard", id: 337 },
  { name: "Mewan", category: "Zaw", type: "standard", id: 338 },
  { name: "Mios", category: "Blade And Whip", type: "standard", id: 339 },
  { name: "Mire", category: "Swords", type: "standard", id: 340 },
  { name: "Miter", category: "Assault Rifle", type: "standard", id: 341 },
  { name: "Morgha", category: "Archgun", type: "standard", id: 342 },
  { name: "Multron", category: "SENTINEL WEAPON", type: "standard", id: 343 },
  { name: "Mutalist Cernos", category: "Bow", type: "standard", id: 344 },
  {
    name: "Mutalist Quanta",
    category: "Assault Rifle",
    type: "standard",
    id: 345,
  },
  { name: "Nagantaka", category: "Bow", type: "standard", id: 346 },
  { name: "Nagantaka Prime", category: "Bow", type: "prime", id: 347 },
  { name: "Nami Skyla", category: "Dual Swords", type: "standard", id: 348 },
  { name: "Nami Skyla Prime", category: "Dual Swords", type: "prime", id: 349 },
  { name: "Nami Solo", category: "Machetes", type: "standard", id: 350 },
  { name: "Nataruk", category: "Bow", type: "standard", id: 351 },
  { name: "Nepheri", category: "Dual Daggers", type: "standard", id: 352 },
  { name: "Nikana", category: "Nikanas", type: "standard", id: 353 },
  { name: "Nikana Prime", category: "Nikanas", type: "prime", id: 354 },
  { name: "Ninkondi", category: "Nunchaku", type: "standard", id: 355 },
  { name: "Ninkondi Prime", category: "Nunchaku", type: "prime", id: 356 },
  { name: "Noctua", category: "Tome", type: "standard", id: 357 },
  { name: "Nukor", category: "Pistol", type: "standard", id: 358 },
  { name: "Obex", category: "Sparring", type: "standard", id: 359 },
  { name: "Ocucor", category: "Pistol", type: "standard", id: 360 },
  { name: "Ogris", category: "Unique", type: "standard", id: 361 },
  { name: "Ohma", category: "Tonfas", type: "standard", id: 362 },
  { name: "Okina", category: "Dual Daggers", type: "standard", id: 363 },
  { name: "Okina Prime", category: "Dual Daggers", type: "prime", id: 364 },
  { name: "Onorix", category: "MELEE", type: "standard", id: 365 },
  { name: "Onos", category: "Pistol", type: "standard", id: 366 },
  { name: "Ooltha", category: "Zaw", type: "standard", id: 367 },
  { name: "Opticor", category: "Unique", type: "standard", id: 368 },
  { name: "Opticor Vandal", category: "Unique", type: "standard", id: 369 },
  { name: "Orthos", category: "Polearms", type: "standard", id: 370 },
  { name: "Orthos Prime", category: "Polearms", type: "prime", id: 371 },
  { name: "Orvius", category: "Glaives", type: "standard", id: 372 },
  { name: "Pandero", category: "Pistol", type: "standard", id: 373 },
  { name: "Pandero Prime", category: "Pistol", type: "prime", id: 374 },
  { name: "Pangolin Prime", category: "Swords", type: "prime", id: 375 },
  { name: "Pangolin Sword", category: "Swords", type: "standard", id: 376 },
  { name: "Panthera", category: "Assault Rifle", type: "standard", id: 377 },
  { name: "Panthera Prime", category: "Assault Rifle", type: "prime", id: 378 },
  { name: "Paracesis", category: "Heavy Blade", type: "standard", id: 379 },
  { name: "Paracyst", category: "Assault Rifle", type: "standard", id: 380 },
  { name: "Paris", category: "Bow", type: "standard", id: 381 },
  { name: "Paris Prime", category: "Bow", type: "prime", id: 382 },
  { name: "Pathocyst", category: "Glaives", type: "standard", id: 383 },
  { name: "Pennant", category: "Two-Handed Nikana", type: "standard", id: 384 },
  { name: "Penta", category: "Unique", type: "standard", id: 385 },
  { name: "Perigale", category: "Sniper", type: "standard", id: 386 },
  { name: "Phaedra", category: "Archgun", type: "standard", id: 387 },
  { name: "Phage", category: "Shotgun", type: "standard", id: 388 },
  { name: "Phantasma", category: "Shotgun", type: "standard", id: 389 },
  { name: "Phantasma Prime", category: "Shotgun", type: "prime", id: 390 },
  { name: "Phenmor", category: "Assault Rifle", type: "standard", id: 391 },
  { name: "Plague Keewar", category: "Zaw", type: "standard", id: 392 },
  { name: "Plague Kripath", category: "Zaw", type: "standard", id: 393 },
  { name: "Plasma Sword", category: "Swords", type: "standard", id: 394 },
  { name: "Plinx", category: "Pistol", type: "standard", id: 395 },
  { name: "Pox", category: "Thrown", type: "standard", id: 396 },
  { name: "Praedos", category: "Tonfas", type: "standard", id: 397 },
  {
    name: "Prime Laser Rifle",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 398,
  },
  { name: "Prisma Angstrum", category: "Pistol", type: "standard", id: 399 },
  { name: "Prisma Burst Laser", category: "Pistol", type: "standard", id: 400 },
  {
    name: "Prisma Dual Cleavers",
    category: "Dual Swords",
    type: "standard",
    id: 401,
  },
  {
    name: "Prisma Dual Decurions",
    category: "Archgun",
    type: "standard",
    id: 402,
  },
  {
    name: "Prisma Gorgon",
    category: "Assault Rifle",
    type: "standard",
    id: 403,
  },
  {
    name: "Prisma Grakata",
    category: "Assault Rifle",
    type: "standard",
    id: 404,
  },
  {
    name: "Prisma Grinlok",
    category: "Assault Rifle",
    type: "standard",
    id: 405,
  },
  { name: "Prisma Lenz", category: "Bow", type: "standard", id: 406 },
  { name: "Prisma Machete", category: "Machetes", type: "standard", id: 407 },
  { name: "Prisma Obex", category: "Sparring", type: "standard", id: 408 },
  { name: "Prisma Ohma", category: "Tonfas", type: "standard", id: 409 },
  { name: "Prisma Skana", category: "Swords", type: "standard", id: 410 },
  {
    name: "Prisma Tetra",
    category: "Assault Rifle",
    type: "standard",
    id: 411,
  },
  {
    name: "Prisma Twin Gremlins",
    category: "Pistol",
    type: "standard",
    id: 412,
  },
  { name: "Prisma Veritux", category: "MELEE", type: "standard", id: 413 },
  { name: "Proboscis Cernos", category: "Bow", type: "standard", id: 414 },
  { name: "Prova", category: "Machetes", type: "standard", id: 415 },
  { name: "Prova Vandal", category: "Machetes", type: "standard", id: 416 },
  { name: "Pulmonars", category: "Nunchaku", type: "standard", id: 417 },
  { name: "Pupacyst", category: "Polearms", type: "standard", id: 418 },
  { name: "Pyrana", category: "Pistol", type: "standard", id: 419 },
  { name: "Pyrana Prime", category: "Pistol", type: "prime", id: 420 },
  { name: "Quanta", category: "Assault Rifle", type: "standard", id: 421 },
  {
    name: "Quanta Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 422,
  },
  { name: "Quartakk", category: "Assault Rifle", type: "standard", id: 423 },
  { name: "Quassus", category: "Warfans", type: "standard", id: 424 },
  { name: "Quatz", category: "Pistol", type: "standard", id: 425 },
  { name: "Quellor", category: "Assault Rifle", type: "standard", id: 426 },
  { name: "Rabvee", category: "Zaw", type: "standard", id: 427 },
  { name: "Rakta Ballistica", category: "Pistol", type: "standard", id: 428 },
  { name: "Rakta Cernos", category: "Bow", type: "standard", id: 429 },
  { name: "Rakta Dark Dagger", category: "Daggers", type: "standard", id: 430 },
  { name: "Rathbone", category: "MELEE", type: "standard", id: 431 },
  { name: "Rattleguts", category: "Kitgun", type: "standard", id: 432 },
  { name: "Rauta", category: "Shotgun", type: "standard", id: 433 },
  { name: "Reaper Prime", category: "Scythes", type: "prime", id: 434 },
  { name: "Redeemer", category: "Gunblade", type: "standard", id: 435 },
  { name: "Redeemer Prime", category: "Gunblade", type: "prime", id: 436 },
  { name: "Regulators", category: "Pistol", type: "standard", id: 437 },
  { name: "Regulators Prime", category: "Pistol", type: "prime", id: 438 },
  { name: "Ripkas", category: "Claws", type: "standard", id: 439 },
  { name: "Rubico", category: "Sniper", type: "standard", id: 440 },
  { name: "Rubico Prime", category: "Sniper", type: "prime", id: 441 },
  { name: "Rumblejack", category: "Daggers", type: "standard", id: 442 },
  { name: "Ruvox", category: "Fists", type: "standard", id: 443 },
  { name: "Sampotes", category: "Hammers", type: "standard", id: 444 },
  { name: "Sancti Castanas", category: "Thrown", type: "standard", id: 445 },
  { name: "Sancti Magistar", category: "Hammers", type: "standard", id: 446 },
  { name: "Sancti Tigris", category: "Shotgun", type: "standard", id: 447 },
  { name: "Sarofang", category: "Heavy Blade", type: "standard", id: 448 },
  { name: "Sarpa", category: "Gunblade", type: "standard", id: 449 },
  { name: "Scindo", category: "Heavy Blade", type: "standard", id: 450 },
  { name: "Scindo Prime", category: "Heavy Blade", type: "prime", id: 451 },
  { name: "Scoliac", category: "Whips", type: "standard", id: 452 },
  { name: "Scourge", category: "Speargun", type: "standard", id: 453 },
  { name: "Scourge Prime", category: "Speargun", type: "prime", id: 454 },
  { name: "Secura Dual Cestra", category: "Pistol", type: "standard", id: 455 },
  { name: "Secura Lecta", category: "Whips", type: "standard", id: 456 },
  { name: "Secura Penta", category: "Unique", type: "standard", id: 457 },
  { name: "Seer", category: "Pistol", type: "standard", id: 458 },
  { name: "Sepfahn", category: "Zaw", type: "standard", id: 459 },
  { name: "Sepulcrum", category: "Pistol", type: "standard", id: 460 },
  { name: "Serro", category: "Polearms", type: "standard", id: 461 },
  { name: "Shadow Claws", category: "MELEE", type: "standard", id: 462 },
  { name: "Shadow Claws Prime", category: "MELEE", type: "prime", id: 463 },
  { name: "Shaku", category: "Nunchaku", type: "standard", id: 464 },
  { name: "Shedu", category: "Assault Rifle", type: "standard", id: 465 },
  { name: "Sheev", category: "Daggers", type: "standard", id: 466 },
  { name: "Sibear", category: "Hammers", type: "standard", id: 467 },
  { name: "Sicarus", category: "Pistol", type: "standard", id: 468 },
  { name: "Sicarus Prime", category: "Pistol", type: "prime", id: 469 },
  {
    name: "Sigma & Octantis",
    category: "Sword And Shield",
    type: "standard",
    id: 470,
  },
  {
    name: "Silva & Aegis",
    category: "Sword And Shield",
    type: "standard",
    id: 471,
  },
  {
    name: "Silva & Aegis Prime",
    category: "Sword And Shield",
    type: "prime",
    id: 472,
  },
  { name: "Simulor", category: "Assault Rifle", type: "standard", id: 473 },
  { name: "Skana", category: "Swords", type: "standard", id: 474 },
  { name: "Skana Prime", category: "Swords", type: "prime", id: 475 },
  { name: "Skiajati", category: "Nikanas", type: "standard", id: 476 },
  { name: "Slaytra", category: "Machetes", type: "standard", id: 477 },
  { name: "Snipetron", category: "Sniper", type: "standard", id: 478 },
  { name: "Snipetron Vandal", category: "Sniper", type: "standard", id: 479 },
  { name: "Sobek", category: "Shotgun", type: "standard", id: 480 },
  { name: "Soma", category: "Assault Rifle", type: "standard", id: 481 },
  { name: "Soma Prime", category: "Assault Rifle", type: "prime", id: 482 },
  { name: "Sonicor", category: "Pistol", type: "standard", id: 483 },
  { name: "Spectra", category: "Pistol", type: "standard", id: 484 },
  { name: "Spectra Vandal", category: "Pistol", type: "standard", id: 485 },
  { name: "Spira", category: "Thrown", type: "standard", id: 486 },
  { name: "Spira Prime", category: "Thrown", type: "prime", id: 487 },
  { name: "Sporelacer", category: "Kitgun", type: "standard", id: 488 },
  { name: "Sporothrix", category: "Sniper", type: "standard", id: 489 },
  { name: "Stahlta", category: "Assault Rifle", type: "standard", id: 490 },
  { name: "Staticor", category: "Pistol", type: "standard", id: 491 },
  { name: "Steflos", category: "Shotgun", type: "standard", id: 492 },
  { name: "Stinger", category: "SENTINEL WEAPON", type: "standard", id: 493 },
  { name: "Stradavar", category: "Assault Rifle", type: "standard", id: 494 },
  {
    name: "Stradavar Prime",
    category: "Assault Rifle",
    type: "prime",
    id: 495,
  },
  { name: "Stropha", category: "Gunblade", type: "standard", id: 496 },
  { name: "Strun", category: "Shotgun", type: "standard", id: 497 },
  { name: "Strun Prime", category: "Shotgun", type: "prime", id: 498 },
  { name: "Strun Wraith", category: "Shotgun", type: "standard", id: 499 },
  { name: "Stubba", category: "Pistol", type: "standard", id: 500 },
  { name: "Stug", category: "Pistol", type: "standard", id: 501 },
  { name: "Sun & Moon", category: "MELEE", type: "standard", id: 502 },
  { name: "Supra", category: "Assault Rifle", type: "standard", id: 503 },
  {
    name: "Supra Vandal",
    category: "Assault Rifle",
    type: "standard",
    id: 504,
  },
  { name: "Sweeper", category: "SENTINEL WEAPON", type: "standard", id: 505 },
  {
    name: "Sweeper Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 506,
  },
  { name: "Syam", category: "Nikanas", type: "standard", id: 507 },
  { name: "Sybaris", category: "Assault Rifle", type: "standard", id: 508 },
  { name: "Sybaris Prime", category: "Assault Rifle", type: "prime", id: 509 },
  { name: "Sydon", category: "Polearms", type: "standard", id: 510 },
  { name: "Synapse", category: "Assault Rifle", type: "standard", id: 511 },
  { name: "Synoid Gammacor", category: "Pistol", type: "standard", id: 512 },
  { name: "Synoid Heliocor", category: "Hammers", type: "standard", id: 513 },
  {
    name: "Synoid Simulor",
    category: "Assault Rifle",
    type: "standard",
    id: 514,
  },
  { name: "Talons", category: "Thrown", type: "standard", id: 515 },
  { name: "Tatsu", category: "Two-Handed Nikana", type: "standard", id: 516 },
  {
    name: "Tatsu Prime",
    category: "Two-Handed Nikana",
    type: "prime",
    id: 517,
  },
  { name: "Tazicor", category: "SENTINEL WEAPON", type: "standard", id: 518 },
  { name: "Tekko", category: "Fists", type: "standard", id: 519 },
  { name: "Tekko Prime", category: "Fists", type: "prime", id: 520 },
  { name: "Telos Akbolto", category: "Pistol", type: "standard", id: 521 },
  { name: "Telos Boltace", category: "Tonfas", type: "standard", id: 522 },
  {
    name: "Telos Boltor",
    category: "Assault Rifle",
    type: "standard",
    id: 523,
  },
  {
    name: "Tenet Agendus",
    category: "Sword And Shield",
    type: "standard",
    id: 524,
  },
  {
    name: "Tenet Arca Plasmor",
    category: "Shotgun",
    type: "standard",
    id: 525,
  },
  { name: "Tenet Cycron", category: "Pistol", type: "standard", id: 526 },
  { name: "Tenet Detron", category: "Pistol", type: "standard", id: 527 },
  { name: "Tenet Diplos", category: "Pistol", type: "standard", id: 528 },
  { name: "Tenet Envoy", category: "Unique", type: "standard", id: 529 },
  { name: "Tenet Exec", category: "Heavy Blade", type: "standard", id: 530 },
  { name: "Tenet Ferrox", category: "Speargun", type: "standard", id: 531 },
  {
    name: "Tenet Flux Rifle",
    category: "Assault Rifle",
    type: "standard",
    id: 532,
  },
  {
    name: "Tenet Glaxion",
    category: "Assault Rifle",
    type: "standard",
    id: 533,
  },
  { name: "Tenet Grigori", category: "Scythes", type: "standard", id: 534 },
  {
    name: "Tenet Livia",
    category: "Two-Handed Nikana",
    type: "standard",
    id: 535,
  },
  { name: "Tenet Plinx", category: "Pistol", type: "standard", id: 536 },
  { name: "Tenet Spirex", category: "Pistol", type: "standard", id: 537 },
  { name: "Tenet Tetra", category: "Assault Rifle", type: "standard", id: 538 },
  { name: "Tenora", category: "Assault Rifle", type: "standard", id: 539 },
  { name: "Tenora Prime", category: "Assault Rifle", type: "prime", id: 540 },
  { name: "Tetra", category: "Assault Rifle", type: "standard", id: 541 },
  { name: "Tiberon", category: "Assault Rifle", type: "standard", id: 542 },
  { name: "Tiberon Prime", category: "Assault Rifle", type: "prime", id: 543 },
  { name: "Tigris", category: "Shotgun", type: "standard", id: 544 },
  { name: "Tigris Prime", category: "Shotgun", type: "prime", id: 545 },
  { name: "Tipedo", category: "Staves", type: "standard", id: 546 },
  { name: "Tipedo Prime", category: "Staves", type: "prime", id: 547 },
  { name: "Tombfinger", category: "Kitgun", type: "standard", id: 548 },
  { name: "Tonbo", category: "Polearms", type: "standard", id: 549 },
  { name: "Tonkor", category: "Unique", type: "standard", id: 550 },
  { name: "Torid", category: "Unique", type: "standard", id: 551 },
  { name: "Trumna", category: "Assault Rifle", type: "standard", id: 552 },
  { name: "Twin Basolk", category: "Dual Swords", type: "standard", id: 553 },
  { name: "Twin Grakatas", category: "Pistol", type: "standard", id: 554 },
  { name: "Twin Gremlins", category: "Pistol", type: "standard", id: 555 },
  { name: "Twin Kohmak", category: "Pistol", type: "standard", id: 556 },
  { name: "Twin Krohkur", category: "Dual Swords", type: "standard", id: 557 },
  { name: "Twin Rogga", category: "Pistol", type: "standard", id: 558 },
  { name: "Twin Vipers", category: "Pistol", type: "standard", id: 559 },
  { name: "Twin Vipers Wraith", category: "Pistol", type: "standard", id: 560 },
  { name: "Tysis", category: "Pistol", type: "standard", id: 561 },
  { name: "Valkyr Prime Talons", category: "MELEE", type: "prime", id: 562 },
  { name: "Valkyr Talons", category: "MELEE", type: "standard", id: 563 },
  { name: "Vastilok", category: "Gunblade", type: "standard", id: 564 },
  { name: "Vasto", category: "Pistol", type: "standard", id: 565 },
  { name: "Vasto Prime", category: "Pistol", type: "prime", id: 566 },
  { name: "Vaykor Hek", category: "Shotgun", type: "standard", id: 567 },
  { name: "Vaykor Marelok", category: "Pistol", type: "standard", id: 568 },
  { name: "Vaykor Sydon", category: "Polearms", type: "standard", id: 569 },
  { name: "Vectis", category: "Sniper", type: "standard", id: 570 },
  { name: "Vectis Prime", category: "Sniper", type: "prime", id: 571 },
  { name: "Veldt", category: "Assault Rifle", type: "standard", id: 572 },
  { name: "Velocitus", category: "Archgun", type: "standard", id: 573 },
  { name: "Velox", category: "Pistol", type: "standard", id: 574 },
  { name: "Velox Prime", category: "Pistol", type: "prime", id: 575 },
  { name: "Venato", category: "Scythes", type: "standard", id: 576 },
  { name: "Venka", category: "Claws", type: "standard", id: 577 },
  { name: "Venka Prime", category: "Claws", type: "prime", id: 578 },
  { name: "Verdilac", category: "Whips", type: "standard", id: 579 },
  { name: "Verglas", category: "SENTINEL WEAPON", type: "standard", id: 580 },
  {
    name: "Verglas Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 581,
  },
  { name: "Vericres", category: "Warfans", type: "standard", id: 582 },
  { name: "Veritux", category: "MELEE", type: "standard", id: 583 },
  { name: "Vermisplicer", category: "Kitgun", type: "standard", id: 584 },
  { name: "Viper", category: "Pistol", type: "standard", id: 585 },
  { name: "Viper Wraith", category: "Pistol", type: "standard", id: 586 },
  { name: "Vitrica", category: "Heavy Blade", type: "standard", id: 587 },
  { name: "Volnus", category: "Hammers", type: "standard", id: 588 },
  { name: "Volnus Prime", category: "Hammers", type: "prime", id: 589 },
  { name: "Vulcax", category: "SENTINEL WEAPON", type: "standard", id: 590 },
  { name: "Vulkar", category: "Sniper", type: "standard", id: 591 },
  { name: "Vulkar Wraith", category: "Sniper", type: "standard", id: 592 },
  { name: "Vulklok", category: "SENTINEL WEAPON", type: "standard", id: 593 },
  { name: "War", category: "Heavy Blade", type: "standard", id: 594 },
  { name: "Wolf Sledge", category: "Hammers", type: "standard", id: 595 },
  { name: "Xoris", category: "Glaives", type: "standard", id: 596 },
  { name: "Zakti", category: "Pistol", type: "standard", id: 597 },
  { name: "Zakti Prime", category: "Pistol", type: "prime", id: 598 },
  { name: "Zarr", category: "Unique", type: "standard", id: 599 },
  { name: "Zenistar", category: "Heavy Blade", type: "standard", id: 600 },
  { name: "Zenith", category: "Assault Rifle", type: "standard", id: 601 },
  { name: "Zhuge", category: "Bow", type: "standard", id: 602 },
  { name: "Zhuge Prime", category: "Bow", type: "prime", id: 603 },
  { name: "Zylok", category: "Pistol", type: "standard", id: 604 },
  { name: "Zylok Prime", category: "Pistol", type: "prime", id: 605 },
  { name: "Zymos", category: "Pistol", type: "standard", id: 606 },
  {
    name: "Deth Machine Rifle Prime",
    category: "SENTINEL WEAPON",
    type: "prime",
    id: 607,
  },
];
